"use client";

import Link from "next/link";
import { ArrowUpRight, CalendarDays, Check, Clock3, MoreHorizontal, Quote, SunMedium } from "lucide-react";
import { modules } from "@/lib/modules";

const tasks = [{ label: "完成英语听力练习", labelEn: "Complete listening practice", time: "09:00", done: true }, { label: "阅读《置身事内》", labelEn: "Read a book", time: "14:30", done: false }, { label: "晚间拉伸 20 分钟", labelEn: "Stretch for 20 minutes", time: "21:00", done: false }];

export function Dashboard({ locale = "zh" }: { locale?: "zh" | "en" }) {
  const now = new Date();
  const isZh = locale === "zh";
  const dateLabel = new Intl.DateTimeFormat(isZh ? "zh-CN" : "en-US", { month: "long", day: "numeric", weekday: "long", year: "numeric" }).format(now);
  return <div className="mx-auto max-w-[1440px]">
    <section className="mb-8 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mb-5 flex items-center gap-2 text-xs font-semibold text-accent"><SunMedium size={15} /> {isZh ? "美好的一天，从这里开始" : "A better day starts here"}</div><h1 className="text-[38px] font-extrabold leading-[1.12] sm:text-[48px]">{isZh ? "早上好，Jie" : "Good morning, Jie"} <span className="inline-block">👋</span></h1><p className="mt-3 text-[15px] text-muted">{dateLabel} · {isZh ? "愿你今天也有清晰的方向。" : "Wishing you a clear direction today."}</p></div><div className="flex items-center gap-2 rounded-2xl border border-line bg-white px-4 py-3 shadow-card"><Clock3 size={17} className="text-accent" /><span className="font-sans text-lg font-bold tabular-nums">{now.toLocaleTimeString(isZh ? "zh-CN" : "en-US", { hour: "2-digit", minute: "2-digit" })}</span><span className="text-xs text-muted">{isZh ? "本地时间" : "Local time"}</span></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.55fr_1fr]">
      <article className="overflow-hidden rounded-[24px] bg-ink p-7 text-white shadow-card sm:p-8"><div className="flex items-start justify-between"><div><p className="text-sm text-white/55">{isZh ? "今日提醒" : "Today's reminder"}</p><h2 className="mt-2 text-2xl font-bold">{isZh ? "给重要的事，留一点专注。" : "Give important things your focus."}</h2></div><div className="grid size-10 place-items-center rounded-xl bg-white/10"><CalendarDays size={18} /></div></div><div className="mt-8 flex items-end justify-between"><div><p className="text-5xl font-extrabold tracking-[-0.06em]">2<span className="ml-1 text-2xl text-white/45">/3</span></p><p className="mt-2 text-sm text-white/55">{isZh ? "今日计划已完成" : "of today's plan complete"}</p></div><div className="w-[45%] pb-2"><div className="mb-2 flex justify-between text-[11px] text-white/50"><span>{isZh ? "进度" : "Progress"}</span><span>67%</span></div><div className="h-2 rounded-full bg-white/15"><div className="h-2 w-[67%] rounded-full bg-[#A8A6FF]" /></div></div></div></article>
      <article className="rounded-[24px] border border-line bg-white p-7 shadow-card sm:p-8"><div className="flex items-center gap-2 text-sm font-semibold"><Quote size={16} className="text-accent" /> {isZh ? "AI 每日一句" : "AI daily note"}</div><p className="mt-6 max-w-[310px] font-sans text-[21px] font-semibold leading-[1.35]">{isZh ? "“每天前进一小步，时间会把它变成很远的路。”" : "“Small steps every day add up to remarkable results.”"}</p><p className="mt-5 text-xs text-muted">— {isZh ? "你的长期主义提醒" : "A reminder for your long game"}</p></article>
    </section>
    <section className="mt-10 grid gap-8 xl:grid-cols-[1fr_1.7fr]"><article className="rounded-[24px] border border-line bg-white p-6 shadow-card sm:p-7"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-lg font-bold">{isZh ? "今日计划" : "Today's plan"}</h2><p className="mt-1 text-xs text-muted">{isZh ? "把注意力放在下一步" : "Focus on the next step"}</p></div><button className="text-muted" aria-label={isZh ? "更多" : "More"}><MoreHorizontal size={19} /></button></div><div className="space-y-1">{tasks.map((task) => <div key={task.label} className="flex items-center gap-3 rounded-xl px-1 py-3"><div className={`grid size-5 place-items-center rounded-full border ${task.done ? "border-accent bg-accent text-white" : "border-[#CBD0D6]"}`}>{task.done && <Check size={13} strokeWidth={3} />}</div><div className="min-w-0 flex-1"><p className={`text-sm font-medium ${task.done ? "text-muted line-through" : "text-ink"}`}>{isZh ? task.label : task.labelEn}</p><p className="mt-1 text-xs text-[#A1A6AE]">{task.time}</p></div></div>)}</div><Link href="/today" className="mt-5 flex items-center gap-1 text-sm font-semibold text-accent">{isZh ? "查看完整计划" : "View full plan"} <ArrowUpRight size={15} /></Link></article><div><div className="mb-5 flex items-end justify-between"><div><h2 className="text-lg font-bold">{isZh ? "探索你的工作台" : "Explore your workspace"}</h2><p className="mt-1 text-xs text-muted">{isZh ? "每个模块，都为长期成长留一块空间" : "A space for every part of your long-term growth"}</p></div><span className="hidden text-xs text-muted sm:block">{isZh ? `${modules.length} 个模块` : `${modules.length} modules`}</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{modules.map((item) => <Link key={item.slug} href={`/${item.slug}`} className="group rounded-[20px] border border-line bg-white p-4 shadow-card transition hover:-translate-y-0.5 hover:border-[#C9C8FA] hover:shadow-lg"><div className={`mb-7 grid size-9 place-items-center rounded-xl ${item.tone}`}><item.icon size={17} /></div><h3 className="text-[13px] font-bold">{isZh ? item.label : item.labelEn}</h3><p className="mt-1 line-clamp-1 text-[11px] text-muted">{isZh ? item.meta : item.metaEn}</p></Link>)}</div></div></section>
  </div>;
}
