import { ExternalLink, X } from "lucide-react";
import type { NewsArticle } from "../types";
import { formatNewsDateTime } from "../utils";

export function NewsDetail({ article, onClose }: { article: NewsArticle; onClose: () => void }) {
  const summary = article.aiSummary;
  return <div className="fixed inset-0 z-40 grid place-items-center bg-ink/25 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-line bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold text-accent">{article.sourceName} · {formatNewsDateTime(article.publishedAt)}</p><h2 className="mt-3 text-2xl font-extrabold leading-9">{article.originalTitle}</h2></div><button onClick={onClose} className="grid size-9 place-items-center rounded-xl bg-canvas text-muted hover:text-ink"><X size={17} /></button></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><section className="rounded-2xl bg-canvas p-4"><p className="text-xs font-bold text-accent">发生了什么</p><p className="mt-2 text-sm leading-6">{summary?.whatHappened ?? article.description ?? "当前来源未提供摘要。"}</p></section><section className="rounded-2xl bg-canvas p-4"><p className="text-xs font-bold text-accent">为什么重要</p><p className="mt-2 text-sm leading-6">{summary?.whyItMatters ?? "暂无足够公开资料判断。"}</p></section></div><div className="mt-5 space-y-5"><DetailList title="关键事实" items={summary?.confirmedFacts ?? ["当前暂无跨来源确认事实。"]} /><DetailList title="目前进展" items={[summary?.currentProgress ?? "暂无进展信息。"]} /><DetailList title="仍需确认" items={summary?.unresolvedQuestions ?? ["请打开原文核实完整信息。"]} /><DetailList title="不同视角" items={summary?.perspectives ?? ["当前来源不足，暂不整理不同视角。"]} /></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4"><p className="text-xs text-muted">标题、来源、发布时间和原文链接来自公开数据源。</p><a href={article.articleUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-bold text-white">打开原文 <ExternalLink size={14} /></a></div></div></div>;
}

function DetailList({ title, items }: { title: string; items: string[] }) { return <section><p className="text-sm font-extrabold">{title}</p><ul className="mt-2 space-y-2 text-sm leading-6 text-muted">{items.map((item, index) => <li key={`${title}-${index}`} className="flex gap-2"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-accent" />{item}</li>)}</ul></section>; }
