import { ExternalLink, Flag, History, Search, Settings2, Star, X } from "lucide-react";
import * as React from "react";
import type { ReactNode } from "react";
import type { NewsArticle, NewsEvent, NewsHistoryItem, NewsSource, NewsTrackedEvent } from "../types";
import { rankNewsEvents } from "../eventClusterService";
import { categoryTone, formatNewsTime } from "../utils";

export function TopStories({ events, onOpen }: { events: NewsEvent[]; onOpen: (articleId: string) => void }) {
  const rankedEvents = rankNewsEvents(events);
  return <section className="rounded-3xl border border-line bg-white p-6 shadow-sm"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-bold text-accent">TODAY&apos;S FOCUS</p><h2 className="mt-2 text-xl font-extrabold">今日重点</h2><p className="mt-1 text-sm text-muted">综合来源数量、报道数量、更新时间和事件状态整理，不代表最终重要性判断。</p></div><span className="text-xs text-muted">今日重点 {Math.min(rankedEvents.length, 10)} / 10</span></div><div className="mt-5 space-y-3">{rankedEvents.length ? rankedEvents.slice(0, 10).map((event) => <button key={event.id} onClick={() => onOpen(event.articleIds[0])} className="w-full rounded-2xl border border-line p-4 text-left transition hover:border-[#BFC4F4] hover:bg-canvas"><div className="flex items-center gap-2 text-xs text-muted"><span className={`rounded-md px-2 py-1 font-semibold ${categoryTone(event.category)}`}>{event.category}</span><span>{event.importance}</span><span>·</span><span>{event.sourceIds.length} 个来源</span><span className="ml-auto">{formatNewsTime(event.lastUpdatedAt)}</span></div><p className="mt-3 font-extrabold leading-6">{event.title}</p><p className="mt-1 line-clamp-2 text-sm leading-6 text-muted">{event.summary}</p><p className="mt-2 text-xs leading-5 text-muted">为什么值得关注：{event.sourceIds.length} 个来源、{event.articleIds.length} 条公开报道，最近于{formatNewsTime(event.lastUpdatedAt)}更新。</p></button>) : <Empty text="当前没有足够的公开新闻形成重点事件。" />}</div></section>;
}

export function TrendingTopics({ events }: { events: NewsEvent[] }) {
  const rankedEvents = rankNewsEvents(events);
  return <section className="rounded-3xl border border-line bg-white p-6 shadow-sm"><div className="flex items-end justify-between"><div><p className="text-xs font-bold text-accent">OPEN SIGNALS</p><h2 className="mt-2 text-xl font-extrabold">今日 TOP10 热点</h2></div><span className="text-xs text-muted">不伪造热度指数</span></div><div className="mt-5 space-y-4">{rankedEvents.slice(0, 10).map((event, index) => <div key={event.id} className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-canvas text-xs font-extrabold text-muted">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{event.title}</p><p className="mt-1 text-xs text-muted">{event.articleIds.length} 条报道 · {event.sourceIds.length} 个来源 · 最近更新 {formatNewsTime(event.lastUpdatedAt)}</p><p className="mt-1 text-xs leading-5 text-muted">为什么重要：{event.sourceIds.length} 个来源、{event.articleIds.length} 条公开报道，且最近于{formatNewsTime(event.lastUpdatedAt)}更新。</p></div></div>)}{!rankedEvents.length ? <Empty text="当前没有可用热点数据。" /> : null}<p className="rounded-xl bg-[#F7F8FA] p-3 text-xs leading-5 text-muted">热点替代指标：相关报道数量、来源数量和更新时间频率。当前没有合法社交平台数据，因此不展示网友比例或情绪占比。</p></div></section>;
}

export function NewsSearch({ query, onQuery, onSubmit }: { query: string; onQuery: (value: string) => void; onSubmit: () => void }) {
  return <form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="flex flex-1 gap-2"><div className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-line bg-white px-3"><Search size={16} className="shrink-0 text-muted" /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="搜索标题、主题或关键词" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none placeholder:text-muted" /></div><button className="rounded-xl bg-ink px-4 py-3 text-sm font-bold text-white">搜索</button></form>;
}

export function NewsCollections({ mode, articles, history, trackedEvents, onOpen, onRemoveHistory, onUntrack }: { mode: "favorites" | "history" | "tracking"; articles: NewsArticle[]; history: NewsHistoryItem[]; trackedEvents: NewsTrackedEvent[]; onOpen: (articleId: string) => void; onRemoveHistory: (articleId: string) => void; onUntrack: (eventId: string) => void }) {
  if (mode === "tracking") return <section className="rounded-3xl border border-line bg-white p-6 shadow-sm"><SectionHeading icon={<Flag size={17} />} title="事件追踪" /><div className="mt-5 space-y-3">{trackedEvents.map((item) => <div key={item.eventId} className="rounded-2xl border border-line p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="font-bold">{item.title}</p><p className="mt-2 text-xs text-muted">{item.articleCount} 条报道 · {item.sourceCount} 个来源 · 最近更新 {formatNewsTime(item.lastUpdatedAt)}</p><p className="mt-2 text-sm leading-6 text-muted">{item.latestProgress}</p></div><button onClick={() => onUntrack(item.eventId)} className="text-xs text-muted hover:text-ink">取消追踪</button></div></div>)}{!trackedEvents.length ? <Empty text="还没有追踪中的事件。" /> : null}</div></section>;
  if (mode === "history") return <section className="rounded-3xl border border-line bg-white p-6 shadow-sm"><SectionHeading icon={<History size={17} />} title="阅读历史" /><div className="mt-5 space-y-2">{history.map((item) => <div key={`${item.articleId}-${item.readAt}`} className="flex items-center gap-3 rounded-xl border border-line p-3"><button onClick={() => onOpen(item.articleId)} className="min-w-0 flex-1 truncate text-left text-sm font-semibold hover:text-accent">{item.title}</button><span className="shrink-0 text-xs text-muted">{item.sourceName}</span><button onClick={() => onRemoveHistory(item.articleId)} aria-label="删除历史" className="shrink-0 text-muted hover:text-ink"><X size={15} /></button></div>)}{!history.length ? <Empty text="还没有阅读历史。" /> : null}</div></section>;
  return <section className="rounded-3xl border border-line bg-white p-6 shadow-sm"><SectionHeading icon={<Star size={17} />} title="我的收藏" /><div className="mt-5 space-y-2">{articles.map((article) => <div key={article.id} className="flex items-center gap-3 rounded-xl border border-line p-3"><button onClick={() => onOpen(article.id)} className="min-w-0 flex-1 truncate text-left text-sm font-semibold hover:text-accent">{article.originalTitle}</button><span className="shrink-0 text-xs text-muted">{article.sourceName}</span><a href={article.articleUrl} target="_blank" rel="noreferrer" className="shrink-0 text-muted hover:text-ink"><ExternalLink size={15} /></a></div>)}{!articles.length ? <Empty text="还没有收藏新闻。" /> : null}</div></section>;
}

export function NewsSourceManager({ sources, onToggle, onAddRss }: { sources: NewsSource[]; onToggle: (id: string) => void; onAddRss: (url: string) => string | undefined }) {
  const [url, setUrl] = React.useState("");
  const [error, setError] = React.useState<string>();
  return <section className="rounded-3xl border border-line bg-white p-6 shadow-sm"><SectionHeading icon={<Settings2 size={17} />} title="来源管理" /><p className="mt-2 text-sm leading-6 text-muted">来源只保存配置和链接，不保存完整新闻正文。停用来源不会影响其他模块。</p><div className="mt-5 rounded-2xl bg-canvas p-4"><p className="text-sm font-bold">添加自己的 RSS</p><p className="mt-1 text-xs leading-5 text-muted">只允许公开的 http/https 地址；请先确认来源允许个人聚合展示。</p><div className="mt-3 flex flex-wrap gap-2"><input value={url} onChange={(event) => { setUrl(event.target.value); setError(undefined); }} placeholder="https://example.com/feed.xml" className="min-w-[240px] flex-1 rounded-xl border border-line bg-white px-3 py-2.5 text-sm outline-none" /><button onClick={() => { const result = onAddRss(url); if (result) setError(result); else setUrl(""); }} className="rounded-xl bg-ink px-4 py-2.5 text-sm font-bold text-white">添加 RSS</button></div>{error ? <p className="mt-2 text-xs text-[#B26F3C]">{error}</p> : null}</div><div className="mt-5 grid gap-3 md:grid-cols-2">{sources.map((source) => <div key={source.id} className="rounded-2xl border border-line p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="font-bold">{source.name}</p><p className="mt-1 text-xs text-muted">{source.sourceType === "gdelt" ? "公开研究数据源" : source.sourceType === "user-rss" ? "用户添加 RSS" : "官方 RSS"} · {source.language}</p><p className="mt-2 text-xs leading-5 text-muted">{source.reliabilityNote}</p>{source.usageNote ? <p className="mt-2 text-xs leading-5 text-[#9A774C]">使用提示：{source.usageNote}</p> : null}</div><button onClick={() => onToggle(source.id)} disabled={source.sourceType === "gdelt"} className={`rounded-lg px-2.5 py-1.5 text-xs font-bold ${source.sourceType === "gdelt" ? "bg-[#E0F0E2] text-[#4F9060]" : source.isEnabled ? "bg-[#E0F0E2] text-[#4F9060]" : "bg-canvas text-muted"}`}>{source.sourceType === "gdelt" ? "默认开启" : source.isEnabled ? "已启用" : "未启用"}</button></div></div>)}</div></section>;
}

function SectionHeading({ icon, title }: { icon: ReactNode; title: string }) { return <div className="flex items-center gap-2 text-accent"><span className="grid size-8 place-items-center rounded-xl bg-[#E7E9FF]">{icon}</span><h2 className="text-xl font-extrabold text-ink">{title}</h2></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-line bg-canvas p-6 text-center text-sm text-muted">{text}</div>; }
