import * as React from "react";
import { Bot, Send, ShieldCheck, Sparkles } from "lucide-react";
import type { FinanceCoachMessage, FinanceKnowledge } from "../types";

interface FinanceCoachProps { knowledge?: FinanceKnowledge; onReply: (question: string, knowledge?: FinanceKnowledge) => Omit<FinanceCoachMessage, "id" | "createdAt" | "role">; }

export function FinanceCoach({ knowledge, onReply }: FinanceCoachProps) {
  const [input, setInput] = React.useState("");
  const [messages, setMessages] = React.useState<FinanceCoachMessage[]>([]);
  const submit = () => { const question = input.trim(); if (!question) return; const now = new Date().toISOString(); const reply = onReply(question, knowledge); setMessages((current) => [...current.slice(-5), { id: `user-${now}`, role: "user", content: question, createdAt: now }, { id: `assistant-${now}`, role: "assistant", ...reply, createdAt: new Date().toISOString() }]); setInput(""); };
  return <section className="rounded-[28px] border border-line bg-[#F8F7FC] p-6 shadow-card sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-bold text-[#7567B6]"><Bot size={16} />AI 理财学习教练</p><h2 className="mt-2 text-xl font-extrabold">把今天的概念讲明白</h2><p className="mt-2 text-sm leading-6 text-muted">当前为本地模拟讲解，适合用来梳理概念和问题。</p></div><div className="grid size-11 place-items-center rounded-2xl bg-white text-[#7567B6] shadow-sm"><Sparkles size={20} /></div></div><div className="mt-6 max-h-[330px] space-y-3 overflow-y-auto pr-1">{messages.length === 0 && <div className="rounded-2xl border border-dashed border-[#D8D1EE] bg-white/70 p-5 text-sm leading-6 text-muted">你可以问：这个概念和日常现金流有什么关系？</div>}{messages.map((message) => <div key={message.id} className={`rounded-2xl p-4 text-sm leading-6 ${message.role === "user" ? "ml-8 bg-ink text-white" : "mr-4 border border-line bg-white text-muted"}`}><p className={message.role === "assistant" ? "font-semibold text-ink" : ""}>{message.content}</p>{message.keyPoints && <ul className="mt-3 space-y-1 text-xs text-muted">{message.keyPoints.map((item) => <li key={item}>· {item}</li>)}</ul>}{message.riskReminder && <p className="mt-3 rounded-xl bg-[#FFF8EC] p-3 text-xs text-[#8A6C49]">{message.riskReminder}</p>}</div>)}</div><div className="mt-5 flex gap-2"><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") submit(); }} placeholder="输入你想理解的财经概念" className="min-w-0 flex-1 rounded-xl border border-line bg-white px-4 py-3 text-sm outline-none transition focus:border-accent" /><button type="button" onClick={submit} className="grid size-11 shrink-0 place-items-center rounded-xl bg-ink text-white transition hover:opacity-90" aria-label="发送问题"><Send size={17} /></button></div><p className="mt-4 flex items-start gap-2 text-xs leading-5 text-muted"><ShieldCheck size={14} className="mt-0.5 shrink-0 text-[#4F9060]" />仅提供财经教育解释，不推荐具体股票、基金、买卖时机或个性化投资方案。</p></section>;
}
