import { CalendarDays, Clock3, Flame, Trophy } from "lucide-react";
import type { FinanceHistoryRecord } from "../types";

interface FinanceHistoryProps { history: Record<string, FinanceHistoryRecord>; currentStreak: number; longestStreak: number; totalStudyMinutes: number; totalCompletedKnowledge: number; onClear: () => void; }

export function FinanceHistory({ history, currentStreak, longestStreak, totalStudyMinutes, totalCompletedKnowledge, onClear }: FinanceHistoryProps) {
  const rows = Object.values(history).sort((a, b) => b.date.localeCompare(a.date)).slice(0, 7);
  return <section className="rounded-[28px] border border-line bg-white p-6 shadow-card sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-bold text-accent"><CalendarDays size={16} />学习记录</p><h2 className="mt-2 text-xl font-extrabold">看见自己的积累</h2></div><button type="button" onClick={onClear} className="text-xs font-semibold text-muted hover:text-[#A95151]">清空记录</button></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-[#F8F7FC] p-4"><Flame size={16} className="text-[#C07C3F]" /><p className="mt-3 text-xs text-muted">当前连续</p><p className="mt-1 font-extrabold">{currentStreak} 天</p></div><div className="rounded-2xl bg-[#F8F7FC] p-4"><Trophy size={16} className="text-[#7567B6]" /><p className="mt-3 text-xs text-muted">最长连续</p><p className="mt-1 font-extrabold">{longestStreak} 天</p></div><div className="rounded-2xl bg-[#F8F7FC] p-4"><Clock3 size={16} className="text-[#3D8290]" /><p className="mt-3 text-xs text-muted">累计时长</p><p className="mt-1 font-extrabold">{totalStudyMinutes} 分钟</p></div><div className="rounded-2xl bg-[#F8F7FC] p-4"><CalendarDays size={16} className="text-[#4F9060]" /><p className="mt-3 text-xs text-muted">已掌握知识</p><p className="mt-1 font-extrabold">{totalCompletedKnowledge} 个</p></div></div><div className="mt-5 space-y-2">{rows.length === 0 && <div className="rounded-2xl border border-dashed border-line p-6 text-center text-sm text-muted">完成今天的学习后，这里会出现历史记录。</div>}{rows.map((record) => <div key={record.date} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-line px-4 py-3 text-sm"><span className="font-bold text-ink">{record.date}</span><span className="text-muted">学习 {record.learnedCount} · 复习 {record.reviewCount} · 正确率 {record.correctRate}%</span><span className={record.targetCompleted ? "font-bold text-[#4F9060]" : "text-muted"}>{record.targetCompleted ? "目标已完成" : "进行中"}</span></div>)}</div></section>;
}
