import * as React from "react";
import { CheckCircle2, CircleHelp, XCircle } from "lucide-react";
import type { FinanceKnowledge } from "../types";

interface KnowledgeQuizProps { knowledge: FinanceKnowledge; onAnswer: (questionId: string, answer: string, correct: boolean) => void; completedQuestionIds: string[]; }

export function KnowledgeQuiz({ knowledge, onAnswer, completedQuestionIds }: KnowledgeQuizProps) {
  const [answers, setAnswers] = React.useState<Record<string, string>>({});
  return <section className="rounded-[28px] border border-line bg-white p-6 shadow-card sm:p-8"><div className="flex items-center justify-between gap-3"><div><p className="flex items-center gap-2 text-sm font-bold text-accent"><CircleHelp size={16} />随堂练习</p><h2 className="mt-2 text-xl font-extrabold">用 3 道题检验今天的理解</h2></div><span className="rounded-full bg-[#F5F3FA] px-3 py-1 text-xs font-bold text-[#7567B6]">即时反馈</span></div><div className="mt-6 space-y-5">{knowledge.quiz.map((question, index) => { const answer = answers[question.id]; const isCorrect = answer === question.correctAnswer; const isAnswered = Boolean(answer); const wasCompleted = completedQuestionIds.includes(question.id); return <div key={question.id} className="rounded-2xl border border-line bg-[#FCFCFD] p-5"><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-[#E9E5FA] text-xs font-extrabold text-[#7567B6]">{index + 1}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold leading-6 text-ink">{question.question}</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{question.options.map((option) => <button key={option} type="button" onClick={() => { if (!isAnswered) { setAnswers((current) => ({ ...current, [question.id]: option })); onAnswer(question.id, option, option === question.correctAnswer); } }} disabled={isAnswered} className={`rounded-xl border px-3 py-2.5 text-left text-sm transition ${isAnswered && option === question.correctAnswer ? "border-[#9BC7A7] bg-[#EAF6EE] text-[#3F7E51]" : isAnswered && option === answer ? "border-[#E1A5A5] bg-[#FFF1F1] text-[#A95151]" : "border-line bg-white text-muted hover:border-accent/50 hover:text-ink"}`}>{option}</button>)}</div>{isAnswered && <div className={`mt-4 flex gap-2 rounded-xl p-3 text-sm leading-6 ${isCorrect ? "bg-[#EAF6EE] text-[#3F7E51]" : "bg-[#FFF1F1] text-[#A95151]"}`}>{isCorrect ? <CheckCircle2 size={17} className="mt-1 shrink-0" /> : <XCircle size={17} className="mt-1 shrink-0" />}<div><p className="font-bold">{isCorrect ? "回答正确" : `正确答案：${question.correctAnswer}`}</p><p className="mt-1">{question.explanation}</p></div></div>}{wasCompleted && !isAnswered && <p className="mt-3 text-xs font-semibold text-muted">本题今天已完成，可切换到下一个知识点继续学习。</p>}</div></div></div>; })}</div></section>;
}
