import type { SpeakingCategory, SpeakingDifficulty, SpeakingScenario } from "./types";

export const speakingScenarios: SpeakingScenario[] = [
  { id: "greeting", titleZh: "日常寒暄", titleEn: "Everyday Greetings", description: "和新朋友自然打招呼，聊聊近况。", category: "daily", difficulty: "beginner", durationMinutes: 5, aiRole: "新朋友", userRole: "你自己", opening: "Hi! It is nice to meet you. How has your day been so far?", openingTranslation: "你好！很高兴认识你。你今天过得怎么样？", vocabulary: ["nice to meet you", "so far", "pretty good"], sentencePatterns: ["It has been...", "I am looking forward to..."] },
  { id: "self-introduction", titleZh: "自我介绍", titleEn: "Self Introduction", description: "用简单清晰的英语介绍自己和兴趣。", category: "daily", difficulty: "beginner", durationMinutes: 5, aiRole: "交流伙伴", userRole: "刚认识的你", opening: "Welcome! Could you tell me a little about yourself?", openingTranslation: "欢迎！可以简单介绍一下你自己吗？", vocabulary: ["work on", "be interested in", "in my free time"], sentencePatterns: ["I am currently...", "One thing I enjoy is..."] },
  { id: "restaurant", titleZh: "餐厅点餐", titleEn: "At a Restaurant", description: "练习点餐、询问推荐和提出特殊要求。", category: "daily", difficulty: "beginner", durationMinutes: 8, aiRole: "服务员", userRole: "顾客", opening: "Good evening. Welcome to our restaurant. Do you have a reservation?", openingTranslation: "晚上好，欢迎光临。请问您有预订吗？", vocabulary: ["reservation", "recommend", "allergic"], sentencePatterns: ["I would like...", "Could you recommend..."] },
  { id: "coffee-shop", titleZh: "咖啡店交流", titleEn: "At a Coffee Shop", description: "在咖啡店完成自然、简短的日常交流。", category: "daily", difficulty: "beginner", durationMinutes: 5, aiRole: "咖啡师", userRole: "顾客", opening: "Good morning! What can I get for you today?", openingTranslation: "早上好！今天想喝点什么？", vocabulary: ["latte", "takeaway", "medium-sized"], sentencePatterns: ["Can I get...", "Could I have that with..."] },
  { id: "hotel", titleZh: "酒店入住", titleEn: "Checking Into a Hotel", description: "练习办理入住、询问设施和解决小问题。", category: "travel", difficulty: "beginner", durationMinutes: 8, aiRole: "前台工作人员", userRole: "旅客", opening: "Welcome to the hotel. May I see your passport, please?", openingTranslation: "欢迎入住。可以看一下您的护照吗？", vocabulary: ["check in", "reservation", "room key"], sentencePatterns: ["I have a reservation under...", "Is it possible to..."] },
  { id: "airport", titleZh: "机场与登机", titleEn: "At the Airport", description: "完成值机、行李托运和登机前沟通。", category: "travel", difficulty: "intermediate", durationMinutes: 10, aiRole: "值机工作人员", userRole: "乘客", opening: "Good morning. Where are you flying today?", openingTranslation: "早上好。您今天要飞往哪里？", vocabulary: ["boarding pass", "baggage", "aisle seat"], sentencePatterns: ["I am flying to...", "Could I have a seat..."] },
  { id: "directions", titleZh: "问路", titleEn: "Asking for Directions", description: "在城市中礼貌地询问路线和交通方式。", category: "travel", difficulty: "beginner", durationMinutes: 6, aiRole: "路人", userRole: "游客", opening: "Hello. You look a little lost. Can I help you find something?", openingTranslation: "你好。你好像有点迷路了，需要我帮你找什么吗？", vocabulary: ["intersection", "across from", "turn left"], sentencePatterns: ["How do I get to...", "Is it within walking distance?"] },
  { id: "shopping", titleZh: "商店购物", titleEn: "Shopping", description: "询问尺码、价格、颜色并完成购买。", category: "daily", difficulty: "beginner", durationMinutes: 7, aiRole: "店员", userRole: "顾客", opening: "Hi there! Are you looking for anything in particular?", openingTranslation: "你好！你在找什么特别的东西吗？", vocabulary: ["try on", "fit", "on sale"], sentencePatterns: ["Do you have this in...", "I am just looking, thanks."] },
  { id: "meeting", titleZh: "工作会议", titleEn: "Work Meeting", description: "表达观点、提出建议并礼貌回应同事。", category: "work", difficulty: "intermediate", durationMinutes: 10, aiRole: "项目同事", userRole: "团队成员", opening: "Thanks for joining the meeting. What do you think about the current plan?", openingTranslation: "感谢参加会议。你对目前的计划有什么看法？", vocabulary: ["agenda", "priority", "follow up"], sentencePatterns: ["From my perspective...", "I suggest that we..."] },
  { id: "presentation", titleZh: "工作汇报", titleEn: "Project Update", description: "用清晰的结构汇报进展、风险和下一步。", category: "work", difficulty: "advanced", durationMinutes: 12, aiRole: "项目负责人", userRole: "汇报人", opening: "Let us start with your project update. What has been completed so far?", openingTranslation: "我们开始做项目汇报吧。目前已经完成了哪些内容？", vocabulary: ["milestone", "on track", "challenge"], sentencePatterns: ["The main progress is...", "Our next step is..."] },
  { id: "interview", titleZh: "英语面试", titleEn: "Job Interview", description: "练习常见面试问题和有条理的回答。", category: "interview", difficulty: "advanced", durationMinutes: 12, aiRole: "面试官", userRole: "求职者", opening: "Thanks for coming in today. Could you tell me about yourself?", openingTranslation: "感谢你今天来参加面试。可以介绍一下自己吗？", vocabulary: ["strength", "experience", "contribute"], sentencePatterns: ["One of my strengths is...", "In my previous role..."] },
  { id: "phone-call", titleZh: "电话沟通", titleEn: "Phone Call", description: "练习电话开场、确认信息和礼貌结束。", category: "work", difficulty: "intermediate", durationMinutes: 8, aiRole: "客户", userRole: "联系人", opening: "Hello, this is Alex calling from Bright Solutions. Is this a good time to talk?", openingTranslation: "你好，我是 Bright Solutions 的 Alex。现在方便聊几分钟吗？", vocabulary: ["available", "clarify", "get back to you"], sentencePatterns: ["I am calling about...", "Let me make sure I understand..."] },
  { id: "travel-chat", titleZh: "旅行聊天", titleEn: "Travel Conversation", description: "和旅途中遇到的人分享目的地与经历。", category: "travel", difficulty: "intermediate", durationMinutes: 8, aiRole: "旅途中认识的朋友", userRole: "旅行者", opening: "Is this your first time visiting this city?", openingTranslation: "这是你第一次来这座城市吗？", vocabulary: ["landmark", "local food", "recommendation"], sentencePatterns: ["I have always wanted to...", "The best part so far is..."] },
  { id: "party", titleZh: "朋友聚会", titleEn: "At a Gathering", description: "在聚会上自然加入话题并表达个人看法。", category: "daily", difficulty: "intermediate", durationMinutes: 8, aiRole: "朋友的朋友", userRole: "参加聚会的人", opening: "Hey, I do not think we have met before. How do you know the host?", openingTranslation: "嗨，我好像之前没见过你。你是怎么认识主人的？", vocabulary: ["get together", "common interest", "conversation"], sentencePatterns: ["We have known each other...", "That reminds me of..."] },
  { id: "free-talk", titleZh: "自由对话", titleEn: "Free Conversation", description: "从今天的生活开始，进行一段开放式对话。", category: "daily", difficulty: "intermediate", durationMinutes: 10, aiRole: "AI 对话伙伴", userRole: "你自己", opening: "Let us have a relaxed conversation. What has been on your mind lately?", openingTranslation: "我们轻松聊聊吧。最近你在想些什么？", vocabulary: ["lately", "personally", "I suppose"], sentencePatterns: ["Recently, I have been...", "What I mean is..."] },
];

export const difficultyLabels: Record<SpeakingDifficulty, string> = { beginner: "初级", intermediate: "中级", advanced: "高级" };
export const categoryLabels: Record<SpeakingCategory, string> = { daily: "日常", travel: "旅行", work: "职场", interview: "面试" };

