import type { EnglishRecommendation, EnglishWord, MovieRecommendation, RecommendationBase, SeriesRecommendation, SpeechRecommendation } from "./types";

const word = (
  id: string,
  value: string,
  phonetic: string,
  meaningZh: string,
  definitionEn: string,
  partOfSpeech: string,
  collocations: string[],
  exampleSentence: string,
  exampleTranslation: string,
  difficulty: EnglishWord["difficulty"],
  topic: string,
): EnglishWord => ({ id, word: value, phonetic, meaningZh, definitionEn, partOfSpeech, collocations, exampleSentence, exampleTranslation, difficulty, topic });

export const englishWords: EnglishWord[] = [
  word("word-001", "adapt", "/əˈdæpt/", "适应；改编", "to change something so it fits a new situation", "动词", ["adapt to change", "adapt quickly"], "We need to adapt to the new schedule.", "我们需要适应新的时间安排。", "beginner", "成长"),
  word("word-002", "achieve", "/əˈtʃiːv/", "实现；取得", "to successfully reach a goal", "动词", ["achieve a goal", "achieve success"], "Small steps can help you achieve your goal.", "小步行动可以帮助你实现目标。", "beginner", "成长"),
  word("word-003", "approach", "/əˈprəʊtʃ/", "方法；接近", "a way of dealing with a problem or situation", "名词/动词", ["a practical approach", "approach a problem"], "This approach makes learning more enjoyable.", "这种方法让学习更有趣。", "intermediate", "学习"),
  word("word-004", "balance", "/ˈbæləns/", "平衡", "a healthy relationship between different parts", "名词/动词", ["work-life balance", "find a balance"], "I am trying to find a better balance.", "我正在努力找到更好的平衡。", "beginner", "生活"),
  word("word-005", "benefit", "/ˈbenɪfɪt/", "益处；受益", "a good result or advantage", "名词/动词", ["health benefits", "benefit from"], "Reading every day has many benefits.", "每天阅读有很多好处。", "beginner", "生活"),
  word("word-006", "challenge", "/ˈtʃælɪndʒ/", "挑战", "a difficult task that tests your ability", "名词/动词", ["face a challenge", "a new challenge"], "Every challenge is also a chance to grow.", "每个挑战也是成长的机会。", "beginner", "成长"),
  word("word-007", "clarify", "/ˈklærɪfaɪ/", "澄清；说明", "to make something easier to understand", "动词", ["clarify a point", "clarify the details"], "Could you clarify what you mean?", "你可以说明一下你的意思吗？", "intermediate", "沟通"),
  word("word-008", "confident", "/ˈkɒnfɪdənt/", "自信的", "feeling sure about your abilities", "形容词", ["feel confident", "confident speaker"], "She felt confident before the presentation.", "她在演讲前感到很自信。", "beginner", "沟通"),
  word("word-009", "connect", "/kəˈnekt/", "连接；建立联系", "to join or relate things together", "动词", ["connect with people", "connect ideas"], "Stories help us connect with one another.", "故事帮助我们彼此建立联系。", "beginner", "沟通"),
  word("word-010", "consider", "/kənˈsɪdə(r)/", "考虑", "to think carefully about something", "动词", ["consider an option", "consider doing"], "Please consider all the options first.", "请先考虑所有选择。", "beginner", "职场"),
  word("word-011", "create", "/kriˈeɪt/", "创造", "to make something new", "动词", ["create a plan", "create value"], "We can create a simple plan together.", "我们可以一起制定一个简单的计划。", "beginner", "创造"),
  word("word-012", "curious", "/ˈkjʊəriəs/", "好奇的", "wanting to know or learn something", "形容词", ["be curious about", "curious mind"], "Stay curious and keep asking questions.", "保持好奇，不断提出问题。", "beginner", "学习"),
  word("word-013", "decision", "/dɪˈsɪʒən/", "决定", "a choice made after thinking", "名词", ["make a decision", "a difficult decision"], "Making a decision is easier with clear information.", "有清晰的信息后更容易做决定。", "beginner", "职场"),
  word("word-014", "develop", "/dɪˈveləp/", "发展；培养", "to grow or improve over time", "动词", ["develop a habit", "develop skills"], "It takes time to develop a useful habit.", "培养一个有用的习惯需要时间。", "beginner", "成长"),
  word("word-015", "efficient", "/ɪˈfɪʃənt/", "高效的", "working well without wasting time or energy", "形容词", ["an efficient system", "work efficiently"], "A short review can be very efficient.", "简短的复习也可以非常高效。", "intermediate", "职场"),
  word("word-016", "encourage", "/ɪnˈkʌrɪdʒ/", "鼓励", "to give someone support or confidence", "动词", ["encourage someone", "encourage growth"], "Good teachers encourage students to try again.", "好老师会鼓励学生再试一次。", "beginner", "沟通"),
  word("word-017", "essential", "/ɪˈsenʃəl/", "必要的；重要的", "completely necessary or very important", "形容词", ["essential skills", "essential information"], "Sleep is essential for good health.", "睡眠对健康非常重要。", "intermediate", "生活"),
  word("word-018", "focus", "/ˈfəʊkəs/", "专注；重点", "to give your full attention to something", "名词/动词", ["focus on", "main focus"], "Try to focus on one task at a time.", "试着一次专注于一项任务。", "beginner", "学习"),
  word("word-019", "habit", "/ˈhæbɪt/", "习惯", "something you do regularly", "名词", ["build a habit", "daily habit"], "A daily habit is easier to keep when it is small.", "每天的习惯小一些更容易坚持。", "beginner", "生活"),
  word("word-020", "improve", "/ɪmˈpruːv/", "改善；提高", "to become better", "动词", ["improve your English", "improve steadily"], "Practice will improve your listening skills.", "练习会提高你的听力能力。", "beginner", "学习"),
  word("word-021", "include", "/ɪnˈkluːd/", "包括", "to contain something as part of a whole", "动词", ["include examples", "price includes"], "The lesson includes a short review.", "这节课包括一个简短复习。", "beginner", "职场"),
  word("word-022", "influence", "/ˈɪnfluəns/", "影响", "the power to change someone's actions or ideas", "名词/动词", ["have an influence", "influence a decision"], "Books can influence the way we think.", "书籍可以影响我们的思考方式。", "intermediate", "成长"),
  word("word-023", "inspire", "/ɪnˈspaɪə(r)/", "启发；鼓舞", "to make someone want to do something", "动词", ["inspire people", "inspire action"], "Her story inspired me to keep going.", "她的故事鼓舞我继续前进。", "beginner", "励志"),
  word("word-024", "manage", "/ˈmænɪdʒ/", "管理；设法做到", "to control or succeed in doing something", "动词", ["manage time", "manage to do"], "Can you manage your time more carefully?", "你能更仔细地管理时间吗？", "beginner", "职场"),
  word("word-025", "opportunity", "/ˌɒpəˈtjuːnəti/", "机会", "a good chance to do something", "名词", ["a great opportunity", "take an opportunity"], "This course is a good opportunity to practice.", "这门课程是练习的好机会。", "intermediate", "成长"),
  word("word-026", "organize", "/ˈɔːɡənaɪz/", "组织；整理", "to arrange things in a clear way", "动词", ["organize your notes", "organize a meeting"], "I organize my notes after every lesson.", "我每节课后都会整理笔记。", "beginner", "学习"),
  word("word-027", "patient", "/ˈpeɪʃənt/", "耐心的", "able to wait calmly", "形容词", ["be patient", "patient with"], "Be patient with yourself while learning.", "学习时要对自己有耐心。", "beginner", "成长"),
  word("word-028", "prefer", "/prɪˈfɜː(r)/", "更喜欢", "to like one thing more than another", "动词", ["prefer to do", "prefer something to"], "I prefer short lessons in the morning.", "我更喜欢早上的短课。", "beginner", "生活"),
  word("word-029", "prepare", "/prɪˈpeə(r)/", "准备", "to get ready for something", "动词", ["prepare for a test", "prepare a speech"], "She prepared carefully for the interview.", "她为面试做了充分准备。", "beginner", "职场"),
  word("word-030", "progress", "/ˈprəʊɡres/", "进步；进展", "movement toward a better or more developed state", "名词", ["make progress", "steady progress"], "You are making progress every day.", "你每天都在进步。", "beginner", "成长"),
  word("word-031", "purpose", "/ˈpɜːpəs/", "目的；意义", "the reason why something exists or is done", "名词", ["serve a purpose", "sense of purpose"], "Knowing your purpose makes practice easier.", "知道目标会让练习更容易。", "intermediate", "成长"),
  word("word-032", "reflect", "/rɪˈflekt/", "反思；反映", "to think deeply about something", "动词", ["reflect on", "reflect an idea"], "Take a moment to reflect on what you learned.", "花一点时间反思你学到的内容。", "intermediate", "学习"),
  word("word-033", "reliable", "/rɪˈlaɪəbəl/", "可靠的", "able to be trusted or depended on", "形容词", ["a reliable source", "reliable information"], "Use a reliable source for your research.", "研究时要使用可靠来源。", "intermediate", "职场"),
  word("word-034", "resource", "/rɪˈsɔːs/", "资源", "something useful that helps you do something", "名词", ["learning resources", "use a resource"], "This website is a useful learning resource.", "这个网站是很有用的学习资源。", "intermediate", "学习"),
  word("word-035", "respond", "/rɪˈspɒnd/", "回应；响应", "to answer or react to something", "动词", ["respond to a question", "respond quickly"], "Please respond to the message by Friday.", "请在周五前回复消息。", "intermediate", "沟通"),
  word("word-036", "routine", "/ruːˈtiːn/", "日常安排", "a regular way of doing things", "名词", ["daily routine", "morning routine"], "A simple routine keeps me on track.", "简单的日常安排让我保持节奏。", "beginner", "生活"),
  word("word-037", "solution", "/səˈluːʃən/", "解决方案", "an answer to a problem", "名词", ["find a solution", "practical solution"], "We need a practical solution to this problem.", "我们需要一个解决这个问题的实用方案。", "intermediate", "职场"),
  word("word-038", "support", "/səˈpɔːt/", "支持；支撑", "to help someone or something", "名词/动词", ["support a decision", "emotional support"], "Friends can support you when learning feels hard.", "学习困难时朋友可以支持你。", "beginner", "沟通"),
  word("word-039", "valuable", "/ˈvæljuəbəl/", "有价值的", "very useful or important", "形容词", ["valuable experience", "valuable advice"], "Feedback is valuable when it is specific.", "具体的反馈很有价值。", "intermediate", "成长"),
  word("word-040", "achievable", "/əˈtʃiːvəbəl/", "可实现的", "possible to complete successfully", "形容词", ["an achievable goal", "set achievable targets"], "Set an achievable goal for this week.", "为本周设定一个可实现的目标。", "intermediate", "成长"),
  word("word-041", "aware", "/əˈweə(r)/", "意识到的", "knowing about a situation", "形容词", ["be aware of", "raise awareness"], "Be aware of how you spend your attention.", "注意你如何分配自己的注意力。", "intermediate", "生活"),
  word("word-042", "communicate", "/kəˈmjuːnɪkeɪt/", "沟通", "to share information or feelings", "动词", ["communicate clearly", "communicate with"], "Clear words help us communicate better.", "清晰的语言帮助我们更好地沟通。", "intermediate", "沟通"),
  word("word-043", "consistent", "/kənˈsɪstənt/", "持续一致的", "doing something in the same reliable way", "形容词", ["stay consistent", "consistent practice"], "Consistent practice matters more than speed.", "持续练习比速度更重要。", "intermediate", "学习"),
  word("word-044", "context", "/ˈkɒntekst/", "语境；背景", "the situation in which something happens", "名词", ["in context", "provide context"], "The meaning becomes clearer in context.", "放在语境中意思会更清楚。", "intermediate", "学习"),
  word("word-045", "curiosity", "/ˌkjʊəriˈɒsəti/", "好奇心", "a strong desire to know more", "名词", ["spark curiosity", "out of curiosity"], "Curiosity can make a difficult topic interesting.", "好奇心可以让困难的主题变得有趣。", "intermediate", "学习"),
  word("word-046", "discuss", "/dɪˈskʌs/", "讨论", "to talk about something with others", "动词", ["discuss an idea", "discuss with"], "Let's discuss the plan after lunch.", "我们午饭后讨论这个计划吧。", "beginner", "沟通"),
  word("word-047", "effective", "/ɪˈfektɪv/", "有效的", "successful in producing the desired result", "形容词", ["effective method", "highly effective"], "Short daily practice is an effective method.", "每天短时间练习是有效的方法。", "intermediate", "学习"),
  word("word-048", "flexible", "/ˈfleksəbəl/", "灵活的", "able to change or adapt easily", "形容词", ["flexible schedule", "remain flexible"], "A flexible schedule helps on busy days.", "灵活的安排有助于应对忙碌的日子。", "intermediate", "生活"),
  word("word-049", "maintain", "/meɪnˈteɪn/", "维持；保持", "to keep something at the same level", "动词", ["maintain a habit", "maintain focus"], "It is important to maintain your routine.", "保持你的日常安排很重要。", "intermediate", "生活"),
  word("word-050", "opinion", "/əˈpɪnjən/", "观点", "a belief or view about something", "名词", ["express an opinion", "in my opinion"], "In my opinion, practice should be enjoyable.", "在我看来，练习应该是令人愉快的。", "beginner", "沟通"),
  word("word-051", "priority", "/praɪˈɒrəti/", "优先事项", "something that is more important than other things", "名词", ["set a priority", "top priority"], "Your health should be a priority.", "你的健康应该是优先事项。", "intermediate", "生活"),
  word("word-052", "review", "/rɪˈvjuː/", "复习；回顾", "to look at something again carefully", "名词/动词", ["review a lesson", "weekly review"], "A quick review helps new words stay fresh.", "快速复习有助于让新单词保持熟悉。", "beginner", "学习"),
];

const baseRecommendation = <T extends EnglishRecommendation["type"]>(
  id: string,
  type: T,
  titleZh: string,
  titleEn: string,
  coverLabel: string,
  coverTone: string,
  difficulty: EnglishRecommendation["difficulty"],
  topics: string[],
  accent: EnglishRecommendation["accent"],
  summary: string,
  reason: string,
  learningScenes: string[],
): Omit<RecommendationBase, "type"> & { type: T } => ({ id, type, titleZh, titleEn, coverLabel, coverTone, difficulty, topics, accent, summary, reason, learningScenes });

export const speechRecommendations: SpeechRecommendation[] = [
  { ...baseRecommendation("speech-001", "speech", "让原创者脱颖而出的奇妙习惯", "The surprising habits of original thinkers", "ORIGINALS", "from-[#E8E7F7] to-[#C9C8FA]", "intermediate", ["职场", "创造力"], "us", "Adam Grant 讨论原创者如何产生想法并把想法付诸行动。", "适合学习观点表达、举例和职场创新词汇。", ["take action", "embrace failure"]), speaker: "Adam Grant", durationMinutes: 15, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/adam_grant_the_surprising_habits_of_original_thinkers" },
  { ...baseRecommendation("speech-002", "speech", "伟大的领袖如何激励行动", "How great leaders inspire action", "WHY", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["职场", "励志"], "us", "Simon Sinek 用黄金圈模型解释人们为什么会被一个清晰的理由鼓舞。", "适合学习职场沟通、原因表达和演讲结构。", ["start with why", "inspire action"]), speaker: "Simon Sinek", durationMinutes: 18, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action" },
  { ...baseRecommendation("speech-003", "speech", "拖延症患者的大脑", "Inside the mind of a master procrastinator", "PROCRASTINATION", "from-[#F7E5D5] to-[#F1C9A7]", "beginner", ["生活", "时间管理"], "us", "Tim Urban 用幽默的方式拆解拖延、即时满足和长期目标。", "适合学习日常叙事、时间管理和因果关系。", ["put something off", "long-term goal"]), speaker: "Tim Urban", durationMinutes: 14, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/tim_urban_inside_the_mind_of_a_master_procrastinator" },
  { ...baseRecommendation("speech-004", "speech", "学校扼杀创造力吗？", "Do schools kill creativity?", "CREATIVITY", "from-[#E4EDF5] to-[#B8D0E5]", "beginner", ["教育", "创造力"], "uk", "Sir Ken Robinson 讨论教育如何保护孩子的创造力和多样性。", "表达清晰、节奏自然，适合初中级学习者。", ["creative potential", "education system"]), speaker: "Sir Ken Robinson", durationMinutes: 19, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/sir_ken_robinson_do_schools_kill_creativity" },
  { ...baseRecommendation("speech-005", "speech", "如何让别人愿意听你说话", "How to speak so that people want to listen", "LISTEN", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["沟通", "职场"], "uk", "Julian Treasure 分享如何通过声音、语气和同理心提升表达效果。", "适合训练听力、发音和真实沟通场景表达。", ["speak with empathy", "powerful speaking"]), speaker: "Julian Treasure", durationMinutes: 10, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/julian_treasure_how_to_speak_so_that_people_want_to_listen" },
  { ...baseRecommendation("speech-006", "speech", "我的中风与顿悟", "My stroke of insight", "BRAIN", "from-[#F8EBD8] to-[#E9C995]", "advanced", ["大脑", "成长"], "us", "脑科学家 Jill Bolte Taylor 讲述个人经历，以及她对大脑和自我意识的观察。", "适合挑战较长句子、科学词汇和叙事听力。", ["brain function", "a sense of self"]), speaker: "Jill Bolte Taylor", durationMinutes: 18, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/jill_bolte_taylor_my_stroke_of_insight" },
];

export const movieRecommendations: MovieRecommendation[] = [
  { ...baseRecommendation("movie-001", "movie", "心灵捕手", "Good Will Hunting", "GOOD WILL", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["剧情", "励志"], "us", "一位天才青年在友情、天赋和自我成长之间寻找方向。", "对话自然，适合学习情绪与关系表达。", ["give yourself a chance", "it is not your fault"]), year: 1997, genre: "剧情", durationMinutes: 126, url: "https://www.imdb.com/find/?q=Good%20Will%20Hunting" },
  { ...baseRecommendation("movie-002", "movie", "当幸福来敲门", "The Pursuit of Happyness", "HAPPYNESS", "from-[#F8EBD8] to-[#F1C9A7]", "beginner", ["励志", "职场"], "us", "一位父亲在生活压力中坚持追求职业机会和更好的生活。", "语速适中，适合初中级学习者。", ["keep going", "a better life"]), year: 2006, genre: "剧情", durationMinutes: 117, url: "https://www.imdb.com/find/?q=The%20Pursuit%20of%20Happyness" },
  { ...baseRecommendation("movie-003", "movie", "帕丁顿熊", "Paddington", "PADDINGTON", "from-[#F7E5D5] to-[#F5C5B1]", "beginner", ["喜剧", "日常生活"], "uk", "一只来自秘鲁的小熊在伦敦寻找新家的温暖故事。", "发音清晰，适合积累生活场景表达。", ["make yourself at home", "thank you very much"]), year: 2014, genre: "喜剧", durationMinutes: 95, url: "https://www.imdb.com/title/tt1109624/" },
  { ...baseRecommendation("movie-004", "movie", "隐藏人物", "Hidden Figures", "FIGURES", "from-[#E4EDF5] to-[#B8D0E5]", "intermediate", ["职场", "励志"], "us", "三位非裔女性数学家在 NASA 的真实故事。", "适合学习工作沟通与解决问题的表达。", ["do the math", "work together"]), year: 2016, genre: "剧情", durationMinutes: 127, url: "https://www.imdb.com/title/tt4846340/" },
  { ...baseRecommendation("movie-005", "movie", "实习生", "The Intern", "INTERN", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["职场", "日常生活"], "us", "退休后重新进入职场的 Ben，在电商公司展开新的生活。", "适合学习会议、反馈和职场礼貌表达。", ["let me know", "take a look"]), year: 2015, genre: "喜剧", durationMinutes: 121, url: "https://www.imdb.com/title/tt2361509/" },
  { ...baseRecommendation("movie-006", "movie", "国王的演讲", "The King's Speech", "SPEECH", "from-[#F0E7F6] to-[#D4B8E2]", "advanced", ["励志", "沟通"], "uk", "乔治六世在语言治疗师帮助下克服口吃并完成重要演讲。", "适合挑战英式发音与正式表达。", ["find your voice", "speak clearly"]), year: 2010, genre: "剧情", durationMinutes: 118, url: "https://www.imdb.com/title/tt1504320/" },
];

export const seriesRecommendations: SeriesRecommendation[] = [
  { ...baseRecommendation("series-001", "series", "老友记", "Friends", "FRIENDS", "from-[#E8E7F7] to-[#C9C8FA]", "beginner", ["喜剧", "日常生活"], "us", "六位朋友在纽约生活、工作和成长的经典情景喜剧。", "适合反复学习短句和口语搭配。", ["How are you doing?", "sounds good"]), genre: "喜剧", episodeMinutes: 22, seasons: 10, url: "https://www.imdb.com/title/tt0108778/" },
  { ...baseRecommendation("series-002", "series", "摩登家庭", "Modern Family", "FAMILY", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["喜剧", "日常生活"], "us", "三个彼此相关的家庭，用轻松幽默的方式面对生活琐事。", "适合学习真实生活中的语气和表达。", ["You know what?", "That makes sense"]), genre: "喜剧", episodeMinutes: 22, seasons: 11, url: "https://www.imdb.com/title/tt1442437/" },
  { ...baseRecommendation("series-003", "series", "唐顿庄园", "Downton Abbey", "DOWNTON", "from-[#F8EBD8] to-[#E9C995]", "advanced", ["剧情", "英式英语"], "uk", "英国贵族家庭与仆人在二十世纪初的生活故事。", "适合中高级学习者理解礼貌和正式语境。", ["if you don't mind", "quite right"]), genre: "剧情", episodeMinutes: 55, seasons: 6, url: "https://www.imdb.com/title/tt1606375/" },
  { ...baseRecommendation("series-004", "series", "硅谷", "Silicon Valley", "SILICON", "from-[#E4EDF5] to-[#B8D0E5]", "advanced", ["科技", "职场"], "us", "创业团队在科技行业中寻找产品和商业机会的喜剧。", "适合积累科技与职场词汇。", ["ship it", "move forward"]), genre: "喜剧", episodeMinutes: 28, seasons: 6, url: "https://www.imdb.com/title/tt2575988/" },
  { ...baseRecommendation("series-005", "series", "布里奇顿", "Bridgerton", "BRIDGERTON", "from-[#F7E5D5] to-[#F1C9A7]", "advanced", ["剧情", "英式英语"], "uk", "摄政时期伦敦社交季中的爱情、家庭和身份故事。", "适合挑战较丰富的词汇和正式语气。", ["I dare say", "how delightful"]), genre: "剧情", episodeMinutes: 58, seasons: 3, url: "https://www.imdb.com/title/tt8740790/" },
  { ...baseRecommendation("series-006", "series", "小谢尔顿", "Young Sheldon", "SHELDON", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["喜剧", "日常生活"], "us", "天才少年 Sheldon 在家庭和校园中成长的故事。", "适合学习日常叙事和表达观点。", ["I suppose", "that's the point"]), genre: "喜剧", episodeMinutes: 22, seasons: 7, url: "https://www.imdb.com/title/tt6226232/" },
];

export const recommendationData: EnglishRecommendation[] = [...speechRecommendations, ...movieRecommendations, ...seriesRecommendations];
