import type { EnglishRecommendation, EnglishWord, MovieRecommendation, RecommendationBase, SeriesRecommendation, SpeechRecommendation } from "./types";

const word = (
  id: string,
  value: string,
  phonetic: string,
  meaningZh: string,
  definitionEn: string,
  partOfSpeech: string,
  collocations: string[],
  exampleSentence: string,
  exampleTranslation: string,
  difficulty: EnglishWord["difficulty"],
  topic: string,
): EnglishWord => ({ id, word: value, phonetic, meaningZh, definitionEn, partOfSpeech, collocations, exampleSentence, exampleTranslation, difficulty, topic });

export const englishWords: EnglishWord[] = [
  word("word-001", "adapt", "/əˈdæpt/", "适应；改编", "to change something so it fits a new situation", "动词", ["adapt to change", "adapt quickly"], "We need to adapt to the new schedule.", "我们需要适应新的时间安排。", "beginner", "成长"),
  word("word-002", "achieve", "/əˈtʃiːv/", "实现；取得", "to successfully reach a goal", "动词", ["achieve a goal", "achieve success"], "Small steps can help you achieve your goal.", "小步行动可以帮助你实现目标。", "beginner", "成长"),
  word("word-003", "approach", "/əˈprəʊtʃ/", "方法；接近", "a way of dealing with a problem or situation", "名词/动词", ["a practical approach", "approach a problem"], "This approach makes learning more enjoyable.", "这种方法让学习更有趣。", "intermediate", "学习"),
  word("word-004", "balance", "/ˈbæləns/", "平衡", "a healthy relationship between different parts", "名词/动词", ["work-life balance", "find a balance"], "I am trying to find a better balance.", "我正在努力找到更好的平衡。", "beginner", "生活"),
  word("word-005", "benefit", "/ˈbenɪfɪt/", "益处；受益", "a good result or advantage", "名词/动词", ["health benefits", "benefit from"], "Reading every day has many benefits.", "每天阅读有很多好处。", "beginner", "生活"),
  word("word-006", "challenge", "/ˈtʃælɪndʒ/", "挑战", "a difficult task that tests your ability", "名词/动词", ["face a challenge", "a new challenge"], "Every challenge is also a chance to grow.", "每个挑战也是成长的机会。", "beginner", "成长"),
  word("word-007", "clarify", "/ˈklærɪfaɪ/", "澄清；说明", "to make something easier to understand", "动词", ["clarify a point", "clarify the details"], "Could you clarify what you mean?", "你可以说明一下你的意思吗？", "intermediate", "沟通"),
  word("word-008", "confident", "/ˈkɒnfɪdənt/", "自信的", "feeling sure about your abilities", "形容词", ["feel confident", "confident speaker"], "She felt confident before the presentation.", "她在演讲前感到很自信。", "beginner", "沟通"),
  word("word-009", "connect", "/kəˈnekt/", "连接；建立联系", "to join or relate things together", "动词", ["connect with people", "connect ideas"], "Stories help us connect with one another.", "故事帮助我们彼此建立联系。", "beginner", "沟通"),
  word("word-010", "consider", "/kənˈsɪdə(r)/", "考虑", "to think carefully about something", "动词", ["consider an option", "consider doing"], "Please consider all the options first.", "请先考虑所有选择。", "beginner", "职场"),
  word("word-011", "create", "/kriˈeɪt/", "创造", "to make something new", "动词", ["create a plan", "create value"], "We can create a simple plan together.", "我们可以一起制定一个简单的计划。", "beginner", "创造"),
  word("word-012", "curious", "/ˈkjʊəriəs/", "好奇的", "wanting to know or learn something", "形容词", ["be curious about", "curious mind"], "Stay curious and keep asking questions.", "保持好奇，不断提出问题。", "beginner", "学习"),
  word("word-013", "decision", "/dɪˈsɪʒən/", "决定", "a choice made after thinking", "名词", ["make a decision", "a difficult decision"], "Making a decision is easier with clear information.", "有清晰的信息后更容易做决定。", "beginner", "职场"),
  word("word-014", "develop", "/dɪˈveləp/", "发展；培养", "to grow or improve over time", "动词", ["develop a habit", "develop skills"], "It takes time to develop a useful habit.", "培养一个有用的习惯需要时间。", "beginner", "成长"),
  word("word-015", "efficient", "/ɪˈfɪʃənt/", "高效的", "working well without wasting time or energy", "形容词", ["an efficient system", "work efficiently"], "A short review can be very efficient.", "简短的复习也可以非常高效。", "intermediate", "职场"),
  word("word-016", "encourage", "/ɪnˈkʌrɪdʒ/", "鼓励", "to give someone support or confidence", "动词", ["encourage someone", "encourage growth"], "Good teachers encourage students to try again.", "好老师会鼓励学生再试一次。", "beginner", "沟通"),
  word("word-017", "essential", "/ɪˈsenʃəl/", "必要的；重要的", "completely necessary or very important", "形容词", ["essential skills", "essential information"], "Sleep is essential for good health.", "睡眠对健康非常重要。", "intermediate", "生活"),
  word("word-018", "focus", "/ˈfəʊkəs/", "专注；重点", "to give your full attention to something", "名词/动词", ["focus on", "main focus"], "Try to focus on one task at a time.", "试着一次专注于一项任务。", "beginner", "学习"),
  word("word-019", "habit", "/ˈhæbɪt/", "习惯", "something you do regularly", "名词", ["build a habit", "daily habit"], "A daily habit is easier to keep when it is small.", "每天的习惯小一些更容易坚持。", "beginner", "生活"),
  word("word-020", "improve", "/ɪmˈpruːv/", "改善；提高", "to become better", "动词", ["improve your English", "improve steadily"], "Practice will improve your listening skills.", "练习会提高你的听力能力。", "beginner", "学习"),
  word("word-021", "include", "/ɪnˈkluːd/", "包括", "to contain something as part of a whole", "动词", ["include examples", "price includes"], "The lesson includes a short review.", "这节课包括一个简短复习。", "beginner", "职场"),
  word("word-022", "influence", "/ˈɪnfluəns/", "影响", "the power to change someone's actions or ideas", "名词/动词", ["have an influence", "influence a decision"], "Books can influence the way we think.", "书籍可以影响我们的思考方式。", "intermediate", "成长"),
  word("word-023", "inspire", "/ɪnˈspaɪə(r)/", "启发；鼓舞", "to make someone want to do something", "动词", ["inspire people", "inspire action"], "Her story inspired me to keep going.", "她的故事鼓舞我继续前进。", "beginner", "励志"),
  word("word-024", "manage", "/ˈmænɪdʒ/", "管理；设法做到", "to control or succeed in doing something", "动词", ["manage time", "manage to do"], "Can you manage your time more carefully?", "你能更仔细地管理时间吗？", "beginner", "职场"),
  word("word-025", "opportunity", "/ˌɒpəˈtjuːnəti/", "机会", "a good chance to do something", "名词", ["a great opportunity", "take an opportunity"], "This course is a good opportunity to practice.", "这门课程是练习的好机会。", "intermediate", "成长"),
  word("word-026", "organize", "/ˈɔːɡənaɪz/", "组织；整理", "to arrange things in a clear way", "动词", ["organize your notes", "organize a meeting"], "I organize my notes after every lesson.", "我每节课后都会整理笔记。", "beginner", "学习"),
  word("word-027", "patient", "/ˈpeɪʃənt/", "耐心的", "able to wait calmly", "形容词", ["be patient", "patient with"], "Be patient with yourself while learning.", "学习时要对自己有耐心。", "beginner", "成长"),
  word("word-028", "prefer", "/prɪˈfɜː(r)/", "更喜欢", "to like one thing more than another", "动词", ["prefer to do", "prefer something to"], "I prefer short lessons in the morning.", "我更喜欢早上的短课。", "beginner", "生活"),
  word("word-029", "prepare", "/prɪˈpeə(r)/", "准备", "to get ready for something", "动词", ["prepare for a test", "prepare a speech"], "She prepared carefully for the interview.", "她为面试做了充分准备。", "beginner", "职场"),
  word("word-030", "progress", "/ˈprəʊɡres/", "进步；进展", "movement toward a better or more developed state", "名词", ["make progress", "steady progress"], "You are making progress every day.", "你每天都在进步。", "beginner", "成长"),
  word("word-031", "purpose", "/ˈpɜːpəs/", "目的；意义", "the reason why something exists or is done", "名词", ["serve a purpose", "sense of purpose"], "Knowing your purpose makes practice easier.", "知道目标会让练习更容易。", "intermediate", "成长"),
  word("word-032", "reflect", "/rɪˈflekt/", "反思；反映", "to think deeply about something", "动词", ["reflect on", "reflect an idea"], "Take a moment to reflect on what you learned.", "花一点时间反思你学到的内容。", "intermediate", "学习"),
  word("word-033", "reliable", "/rɪˈlaɪəbəl/", "可靠的", "able to be trusted or depended on", "形容词", ["a reliable source", "reliable information"], "Use a reliable source for your research.", "研究时要使用可靠来源。", "intermediate", "职场"),
  word("word-034", "resource", "/rɪˈsɔːs/", "资源", "something useful that helps you do something", "名词", ["learning resources", "use a resource"], "This website is a useful learning resource.", "这个网站是很有用的学习资源。", "intermediate", "学习"),
  word("word-035", "respond", "/rɪˈspɒnd/", "回应；响应", "to answer or react to something", "动词", ["respond to a question", "respond quickly"], "Please respond to the message by Friday.", "请在周五前回复消息。", "intermediate", "沟通"),
  word("word-036", "routine", "/ruːˈtiːn/", "日常安排", "a regular way of doing things", "名词", ["daily routine", "morning routine"], "A simple routine keeps me on track.", "简单的日常安排让我保持节奏。", "beginner", "生活"),
  word("word-037", "solution", "/səˈluːʃən/", "解决方案", "an answer to a problem", "名词", ["find a solution", "practical solution"], "We need a practical solution to this problem.", "我们需要一个解决这个问题的实用方案。", "intermediate", "职场"),
  word("word-038", "support", "/səˈpɔːt/", "支持；支撑", "to help someone or something", "名词/动词", ["support a decision", "emotional support"], "Friends can support you when learning feels hard.", "学习困难时朋友可以支持你。", "beginner", "沟通"),
  word("word-039", "valuable", "/ˈvæljuəbəl/", "有价值的", "very useful or important", "形容词", ["valuable experience", "valuable advice"], "Feedback is valuable when it is specific.", "具体的反馈很有价值。", "intermediate", "成长"),
  word("word-040", "achievable", "/əˈtʃiːvəbəl/", "可实现的", "possible to complete successfully", "形容词", ["an achievable goal", "set achievable targets"], "Set an achievable goal for this week.", "为本周设定一个可实现的目标。", "intermediate", "成长"),
  word("word-041", "aware", "/əˈweə(r)/", "意识到的", "knowing about a situation", "形容词", ["be aware of", "raise awareness"], "Be aware of how you spend your attention.", "注意你如何分配自己的注意力。", "intermediate", "生活"),
  word("word-042", "communicate", "/kəˈmjuːnɪkeɪt/", "沟通", "to share information or feelings", "动词", ["communicate clearly", "communicate with"], "Clear words help us communicate better.", "清晰的语言帮助我们更好地沟通。", "intermediate", "沟通"),
  word("word-043", "consistent", "/kənˈsɪstənt/", "持续一致的", "doing something in the same reliable way", "形容词", ["stay consistent", "consistent practice"], "Consistent practice matters more than speed.", "持续练习比速度更重要。", "intermediate", "学习"),
  word("word-044", "context", "/ˈkɒntekst/", "语境；背景", "the situation in which something happens", "名词", ["in context", "provide context"], "The meaning becomes clearer in context.", "放在语境中意思会更清楚。", "intermediate", "学习"),
  word("word-045", "curiosity", "/ˌkjʊəriˈɒsəti/", "好奇心", "a strong desire to know more", "名词", ["spark curiosity", "out of curiosity"], "Curiosity can make a difficult topic interesting.", "好奇心可以让困难的主题变得有趣。", "intermediate", "学习"),
  word("word-046", "discuss", "/dɪˈskʌs/", "讨论", "to talk about something with others", "动词", ["discuss an idea", "discuss with"], "Let's discuss the plan after lunch.", "我们午饭后讨论这个计划吧。", "beginner", "沟通"),
  word("word-047", "effective", "/ɪˈfektɪv/", "有效的", "successful in producing the desired result", "形容词", ["effective method", "highly effective"], "Short daily practice is an effective method.", "每天短时间练习是有效的方法。", "intermediate", "学习"),
  word("word-048", "flexible", "/ˈfleksəbəl/", "灵活的", "able to change or adapt easily", "形容词", ["flexible schedule", "remain flexible"], "A flexible schedule helps on busy days.", "灵活的安排有助于应对忙碌的日子。", "intermediate", "生活"),
  word("word-049", "maintain", "/meɪnˈteɪn/", "维持；保持", "to keep something at the same level", "动词", ["maintain a habit", "maintain focus"], "It is important to maintain your routine.", "保持你的日常安排很重要。", "intermediate", "生活"),
  word("word-050", "opinion", "/əˈpɪnjən/", "观点", "a belief or view about something", "名词", ["express an opinion", "in my opinion"], "In my opinion, practice should be enjoyable.", "在我看来，练习应该是令人愉快的。", "beginner", "沟通"),
  word("word-051", "priority", "/praɪˈɒrəti/", "优先事项", "something that is more important than other things", "名词", ["set a priority", "top priority"], "Your health should be a priority.", "你的健康应该是优先事项。", "intermediate", "生活"),
  word("word-052", "review", "/rɪˈvjuː/", "复习；回顾", "to look at something again carefully", "名词/动词", ["review a lesson", "weekly review"], "A quick review helps new words stay fresh.", "快速复习有助于让新单词保持熟悉。", "beginner", "学习"),
];

const baseRecommendation = <T extends EnglishRecommendation["type"]>(
  id: string,
  type: T,
  titleZh: string,
  titleEn: string,
  coverLabel: string,
  coverTone: string,
  difficulty: EnglishRecommendation["difficulty"],
  topics: string[],
  accent: EnglishRecommendation["accent"],
  summary: string,
  reason: string,
  learningScenes: string[],
): Omit<RecommendationBase, "type"> & { type: T } => ({ id, type, titleZh, titleEn, coverLabel, coverTone, difficulty, topics, accent, summary, reason, learningScenes });

export const speechRecommendations: SpeechRecommendation[] = [
  { ...baseRecommendation("speech-001", "speech", "让原创者脱颖而出的奇妙习惯", "The surprising habits of original thinkers", "ORIGINALS", "from-[#E8E7F7] to-[#C9C8FA]", "intermediate", ["职场", "创造力"], "us", "Adam Grant 讨论原创者如何产生想法并把想法付诸行动。", "适合学习观点表达、举例和职场创新词汇。", ["take action", "embrace failure"]), speaker: "Adam Grant", durationMinutes: 15, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/adam_grant_the_surprising_habits_of_original_thinkers" },
  { ...baseRecommendation("speech-002", "speech", "伟大的领袖如何激励行动", "How great leaders inspire action", "WHY", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["职场", "励志"], "us", "Simon Sinek 用黄金圈模型解释人们为什么会被一个清晰的理由鼓舞。", "适合学习职场沟通、原因表达和演讲结构。", ["start with why", "inspire action"]), speaker: "Simon Sinek", durationMinutes: 18, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action" },
  { ...baseRecommendation("speech-003", "speech", "拖延症患者的大脑", "Inside the mind of a master procrastinator", "PROCRASTINATION", "from-[#F7E5D5] to-[#F1C9A7]", "beginner", ["生活", "时间管理"], "us", "Tim Urban 用幽默的方式拆解拖延、即时满足和长期目标。", "适合学习日常叙事、时间管理和因果关系。", ["put something off", "long-term goal"]), speaker: "Tim Urban", durationMinutes: 14, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/tim_urban_inside_the_mind_of_a_master_procrastinator" },
  { ...baseRecommendation("speech-004", "speech", "学校扼杀创造力吗？", "Do schools kill creativity?", "CREATIVITY", "from-[#E4EDF5] to-[#B8D0E5]", "beginner", ["教育", "创造力"], "uk", "Sir Ken Robinson 讨论教育如何保护孩子的创造力和多样性。", "表达清晰、节奏自然，适合初中级学习者。", ["creative potential", "education system"]), speaker: "Sir Ken Robinson", durationMinutes: 19, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/sir_ken_robinson_do_schools_kill_creativity" },
  { ...baseRecommendation("speech-005", "speech", "如何让别人愿意听你说话", "How to speak so that people want to listen", "LISTEN", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["沟通", "职场"], "uk", "Julian Treasure 分享如何通过声音、语气和同理心提升表达效果。", "适合训练听力、发音和真实沟通场景表达。", ["speak with empathy", "powerful speaking"]), speaker: "Julian Treasure", durationMinutes: 10, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/julian_treasure_how_to_speak_so_that_people_want_to_listen" },
  { ...baseRecommendation("speech-006", "speech", "我的中风与顿悟", "My stroke of insight", "BRAIN", "from-[#F8EBD8] to-[#E9C995]", "advanced", ["大脑", "成长"], "us", "脑科学家 Jill Bolte Taylor 讲述个人经历，以及她对大脑和自我意识的观察。", "适合挑战较长句子、科学词汇和叙事听力。", ["brain function", "a sense of self"]), speaker: "Jill Bolte Taylor", durationMinutes: 18, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/jill_bolte_taylor_my_stroke_of_insight" },
  { ...baseRecommendation("speech-007", "speech", "脆弱的力量", "The power of vulnerability", "VULNERABILITY", "from-[#F7E5D5] to-[#F1C9A7]", "intermediate", ["沟通", "成长"], "us", "Brené Brown 分享脆弱、连接和真实关系之间的联系。", "适合学习情绪表达、观点解释和个人经历叙述。", ["open up", "build connection"]), speaker: "Brené Brown", durationMinutes: 21, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/brene_brown_the_power_of_vulnerability" },
  { ...baseRecommendation("speech-008", "speech", "把压力变成你的朋友", "How to make stress your friend", "STRESS", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["生活", "健康"], "us", "Kelly McGonigal 解释我们如何重新理解压力，并利用压力带来的能量。", "适合学习因果关系、建议表达和健康话题词汇。", ["cope with stress", "change your mindset"]), speaker: "Kelly McGonigal", durationMinutes: 14, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/kelly_mcgonigal_how_to_make_stress_your_friend" },
  { ...baseRecommendation("speech-009", "speech", "让工作更快乐的秘密", "The happy secret to better work", "HAPPY WORK", "from-[#E4EDF5] to-[#B8D0E5]", "beginner", ["职场", "励志"], "us", "Shawn Achor 讨论积极心态如何影响工作表现和幸福感。", "适合学习职场观点、比较和结果表达。", ["stay positive", "perform better"]), speaker: "Shawn Achor", durationMinutes: 12, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/shawn_achor_the_happy_secret_to_better_work" },
  { ...baseRecommendation("speech-010", "speech", "你的身体语言会改变你是谁", "Your body language may shape who you are", "BODY LANGUAGE", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["沟通", "职场"], "us", "Amy Cuddy 介绍身体姿态、自信感受和社交表现之间的关系。", "适合学习描述、推测和面试沟通表达。", ["feel confident", "make an impression"]), speaker: "Amy Cuddy", durationMinutes: 21, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/amy_cuddy_your_body_language_may_shape_who_you_are" },
  { ...baseRecommendation("speech-011", "speech", "毅力：热情与坚持的力量", "Grit: The power of passion and perseverance", "GRIT", "from-[#F8EBD8] to-[#E9C995]", "intermediate", ["成长", "教育"], "us", "Angela Duckworth 解释长期目标中的毅力、热情与坚持。", "适合学习定义、举例和长期目标表达。", ["keep going", "long-term goal"]), speaker: "Angela Duckworth", durationMinutes: 6, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/angela_lee_duckworth_grit_the_power_of_passion_and_perseverance" },
  { ...baseRecommendation("speech-012", "speech", "进行更好对话的十种方法", "10 ways to have a better conversation", "CONVERSATION", "from-[#E8E7F7] to-[#C9C8FA]", "beginner", ["沟通", "日常生活"], "us", "Celeste Headlee 分享倾听、提问和保持对话平衡的实用方法。", "适合训练日常交流、提问和回应。", ["listen carefully", "keep a conversation going"]), speaker: "Celeste Headlee", durationMinutes: 12, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/celeste_headlee_10_ways_to_have_a_better_conversation" },
  { ...baseRecommendation("speech-013", "speech", "美好生活的关键", "What makes a good life? Lessons from the longest study on happiness", "GOOD LIFE", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["生活", "成长"], "us", "Robert Waldinger 分享长期成人发展研究中关于关系与幸福的发现。", "适合学习总结、观点和生活经验表达。", ["stay connected", "meaningful relationships"]), speaker: "Robert Waldinger", durationMinutes: 13, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/robert_waldinger_what_makes_a_good_life_lessons_from_the_longest_study_on_happiness" },
  { ...baseRecommendation("speech-014", "speech", "内向者的力量", "The power of introverts", "INTROVERTS", "from-[#F7E5D5] to-[#F1C9A7]", "intermediate", ["沟通", "成长"], "us", "Susan Cain 讨论内向特质、独处和创造性思考的价值。", "适合学习比较、解释和个人特点表达。", ["need some quiet", "think deeply"]), speaker: "Susan Cain", durationMinutes: 20, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/susan_cain_the_power_of_introverts" },
  { ...baseRecommendation("speech-015", "speech", "提升倾听能力的五种方法", "5 ways to listen better", "LISTEN BETTER", "from-[#E4EDF5] to-[#B8D0E5]", "beginner", ["沟通", "日常生活"], "uk", "Julian Treasure 讲解如何减少干扰并更主动地倾听。", "适合学习建议、动作表达和日常沟通词汇。", ["pay attention", "listen actively"]), speaker: "Julian Treasure", durationMinutes: 7, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/julian_treasure_5_ways_to_listen_better" },
  { ...baseRecommendation("speech-016", "speech", "睡眠是你的超能力", "Sleep is your superpower", "SLEEP", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["健康", "生活"], "us", "Matthew Walker 介绍睡眠对记忆、健康和日常表现的重要作用。", "适合学习解释、原因和健康建议。", ["get enough sleep", "improve memory"]), speaker: "Matthew Walker", durationMinutes: 19, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/matt_walker_sleep_is_your_superpower" },
  { ...baseRecommendation("speech-017", "speech", "如何开始一场运动", "How to start a movement", "MOVEMENT", "from-[#F8EBD8] to-[#E9C995]", "beginner", ["沟通", "职场"], "us", "Derek Sivers 用一个简单的公共活动说明领导者与参与者如何形成群体。", "适合学习叙事、步骤和团队协作表达。", ["join in", "lead by example"]), speaker: "Derek Sivers", durationMinutes: 3, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/derek_sivers_how_to_start_a_movement" },
  { ...baseRecommendation("speech-018", "speech", "单一故事的危险", "The danger of a single story", "SINGLE STORY", "from-[#E8E7F7] to-[#C9C8FA]", "advanced", ["文化", "沟通"], "us", "Chimamanda Ngozi Adichie 讨论单一叙事如何影响我们理解他人和世界。", "适合挑战抽象观点、文化话题和论证表达。", ["look beyond", "tell a fuller story"]), speaker: "Chimamanda Ngozi Adichie", durationMinutes: 19, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/chimamanda_adichie_the_danger_of_a_single_story" },
  { ...baseRecommendation("speech-019", "speech", "如何系鞋带", "How to tie your shoes", "SMALL SKILL", "from-[#DDEFE4] to-[#B8DEC7]", "beginner", ["生活", "学习"], "us", "Terry Moore 说明一个简单的系鞋带方法，并展示清晰教学的结构。", "适合学习步骤说明、动作词和简短表达。", ["tie a knot", "follow the steps"]), speaker: "Terry Moore", durationMinutes: 3, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/terry_moore_how_to_tie_your_shoes" },
  { ...baseRecommendation("speech-020", "speech", "如何培养自信并帮助他人自信", "How to build your confidence and spark it in others", "CONFIDENCE", "from-[#F7E5D5] to-[#F1C9A7]", "intermediate", ["沟通", "成长"], "us", "Brittany Packnett 分享建立自信、突破限制并支持他人的方法。", "适合学习建议、经历和鼓励表达。", ["speak up", "believe in yourself"]), speaker: "Brittany Packnett Cunningham", durationMinutes: 13, captions: { english: true, bilingual: false }, url: "https://www.ted.com/talks/brittany_packnett_how_to_build_your_confidence_and_spark_it_in_others" },
];

export const movieRecommendations: MovieRecommendation[] = [
  { ...baseRecommendation("movie-001", "movie", "心灵捕手", "Good Will Hunting", "GOOD WILL", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["剧情", "励志"], "us", "一位天才青年在友情、天赋和自我成长之间寻找方向。", "对话自然，适合学习情绪与关系表达。", ["give yourself a chance", "it is not your fault"]), year: 1997, genre: "剧情", durationMinutes: 126, url: "https://www.imdb.com/find/?q=Good%20Will%20Hunting" },
  { ...baseRecommendation("movie-002", "movie", "当幸福来敲门", "The Pursuit of Happyness", "HAPPYNESS", "from-[#F8EBD8] to-[#F1C9A7]", "beginner", ["励志", "职场"], "us", "一位父亲在生活压力中坚持追求职业机会和更好的生活。", "语速适中，适合初中级学习者。", ["keep going", "a better life"]), year: 2006, genre: "剧情", durationMinutes: 117, url: "https://www.imdb.com/find/?q=The%20Pursuit%20of%20Happyness" },
  { ...baseRecommendation("movie-003", "movie", "帕丁顿熊", "Paddington", "PADDINGTON", "from-[#F7E5D5] to-[#F5C5B1]", "beginner", ["喜剧", "日常生活"], "uk", "一只来自秘鲁的小熊在伦敦寻找新家的温暖故事。", "发音清晰，适合积累生活场景表达。", ["make yourself at home", "thank you very much"]), year: 2014, genre: "喜剧", durationMinutes: 95, url: "https://www.imdb.com/title/tt1109624/" },
  { ...baseRecommendation("movie-004", "movie", "隐藏人物", "Hidden Figures", "FIGURES", "from-[#E4EDF5] to-[#B8D0E5]", "intermediate", ["职场", "励志"], "us", "三位非裔女性数学家在 NASA 的真实故事。", "适合学习工作沟通与解决问题的表达。", ["do the math", "work together"]), year: 2016, genre: "剧情", durationMinutes: 127, url: "https://www.imdb.com/title/tt4846340/" },
  { ...baseRecommendation("movie-005", "movie", "实习生", "The Intern", "INTERN", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["职场", "日常生活"], "us", "退休后重新进入职场的 Ben，在电商公司展开新的生活。", "适合学习会议、反馈和职场礼貌表达。", ["let me know", "take a look"]), year: 2015, genre: "喜剧", durationMinutes: 121, url: "https://www.imdb.com/title/tt2361509/" },
  { ...baseRecommendation("movie-006", "movie", "国王的演讲", "The King's Speech", "SPEECH", "from-[#F0E7F6] to-[#D4B8E2]", "advanced", ["励志", "沟通"], "uk", "乔治六世在语言治疗师帮助下克服口吃并完成重要演讲。", "适合挑战英式发音与正式表达。", ["find your voice", "speak clearly"]), year: 2010, genre: "剧情", durationMinutes: 118, url: "https://www.imdb.com/title/tt1504320/" },
  { ...baseRecommendation("movie-007", "movie", "穿普拉达的女王", "The Devil Wears Prada", "PRADA", "from-[#E8E7F7] to-[#C9C8FA]", "intermediate", ["职场", "沟通"], "us", "一位年轻记者进入时尚杂志社，在高压职场中学习沟通与成长。", "适合学习会议、反馈和职场礼貌表达。", ["meet a deadline", "take responsibility"]), year: 2006, genre: "剧情", durationMinutes: 109, url: "https://www.themoviedb.org/movie/350" },
  { ...baseRecommendation("movie-008", "movie", "律政俏佳人", "Legally Blonde", "LEGALLY", "from-[#F7E5D5] to-[#F1C9A7]", "beginner", ["校园", "成长"], "us", "Elle Woods 进入法学院，用坚持和自信证明自己的能力。", "对话清晰，适合学习校园、目标和自我介绍表达。", ["prove yourself", "work hard"]), year: 2001, genre: "喜剧", durationMinutes: 96, url: "https://www.themoviedb.org/movie/8835" },
  { ...baseRecommendation("movie-009", "movie", "楚门的世界", "The Truman Show", "TRUMAN", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["生活", "观点"], "us", "一个普通人的生活被完整记录，他开始重新思考真实、选择和自由。", "适合学习观点表达、质疑和情绪描述。", ["make a choice", "find the truth"]), year: 1998, genre: "喜剧", durationMinutes: 103, url: "https://www.themoviedb.org/movie/37165" },
  { ...baseRecommendation("movie-010", "movie", "阿甘正传", "Forrest Gump", "FORREST", "from-[#E4EDF5] to-[#B8D0E5]", "beginner", ["生活", "励志"], "us", "Forrest 用简单而真诚的方式经历家庭、友情和人生变化。", "语句自然，适合学习叙事和日常情绪表达。", ["keep going", "life changes"]), year: 1994, genre: "剧情", durationMinutes: 142, url: "https://www.themoviedb.org/movie/13" },
  { ...baseRecommendation("movie-011", "movie", "白日梦想家", "The Secret Life of Walter Mitty", "WALTER", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["成长", "旅行"], "us", "Walter 离开熟悉的生活，踏上寻找照片和自我的旅程。", "适合学习旅行、计划和勇气表达。", ["step outside", "take a chance"]), year: 2013, genre: "喜剧", durationMinutes: 114, url: "https://www.themoviedb.org/movie/116745" },
  { ...baseRecommendation("movie-012", "movie", "阳光小美女", "Little Miss Sunshine", "SUNSHINE", "from-[#F8EBD8] to-[#E9C995]", "intermediate", ["家庭", "成长"], "us", "一个家庭为了支持女儿参加比赛，踏上充满摩擦与温情的公路旅行。", "适合学习家庭交流、意见表达和叙事。", ["stick together", "support each other"]), year: 2006, genre: "喜剧", durationMinutes: 102, url: "https://www.themoviedb.org/movie/773" },
  { ...baseRecommendation("movie-013", "movie", "社交网络", "The Social Network", "NETWORK", "from-[#E8E7F7] to-[#C9C8FA]", "advanced", ["职场", "科技"], "us", "一个社交平台的创立引发了合作、竞争和责任之间的冲突。", "适合挑战快速对话、谈判和科技职场词汇。", ["work together", "protect an idea"]), year: 2010, genre: "剧情", durationMinutes: 121, url: "https://www.themoviedb.org/movie/37799" },
  { ...baseRecommendation("movie-014", "movie", "幸福终点站", "The Terminal", "TERMINAL", "from-[#DDEFE4] to-[#B8DEC7]", "beginner", ["日常生活", "沟通"], "us", "一名旅客被困机场，在陌生环境中学习求助、适应和建立关系。", "适合学习机场、请求帮助和日常交流。", ["ask for help", "make yourself comfortable"]), year: 2004, genre: "喜剧", durationMinutes: 128, url: "https://www.themoviedb.org/movie/594" },
  { ...baseRecommendation("movie-015", "movie", "时空恋旅人", "About Time", "ABOUT TIME", "from-[#F7E5D5] to-[#F1C9A7]", "intermediate", ["家庭", "爱情"], "uk", "Tim 学会珍惜平凡日常，并重新理解家庭、关系和时间。", "适合学习家庭对话、回忆和情感表达。", ["make the most of", "spend time together"]), year: 2013, genre: "爱情", durationMinutes: 123, url: "https://www.themoviedb.org/movie/122906" },
  { ...baseRecommendation("movie-016", "movie", "恋爱假期", "The Holiday", "HOLIDAY", "from-[#E4EDF5] to-[#B8D0E5]", "intermediate", ["生活", "关系"], "us", "两位女性交换住所，在新的环境中重新认识生活和感情。", "适合学习社交、计划和关系表达。", ["take a break", "start over"]), year: 2006, genre: "喜剧", durationMinutes: 136, url: "https://www.themoviedb.org/movie/1581" },
  { ...baseRecommendation("movie-017", "movie", "玩具总动员", "Toy Story", "TOY STORY", "from-[#E9E5FA] to-[#CEC5F1]", "beginner", ["家庭", "动画"], "us", "玩具们在孩子离开后面对友情、变化和彼此支持。", "发音清晰，适合学习家庭、友情和简单叙事。", ["stay together", "make a friend"]), year: 1995, genre: "动画", durationMinutes: 81, url: "https://www.themoviedb.org/movie/862" },
  { ...baseRecommendation("movie-018", "movie", "头脑特工队", "Inside Out", "INSIDE OUT", "from-[#F8EBD8] to-[#E9C995]", "beginner", ["家庭", "情绪"], "us", "一个女孩搬家后，内心的情绪们一起帮助她适应新的生活。", "适合学习情绪、变化和家庭沟通词汇。", ["feel left out", "adjust to change"]), year: 2015, genre: "动画", durationMinutes: 95, url: "https://www.themoviedb.org/movie/150540" },
  { ...baseRecommendation("movie-019", "movie", "寻梦环游记", "Coco", "COCO", "from-[#E8E7F7] to-[#C9C8FA]", "beginner", ["家庭", "音乐"], "us", "Miguel 在音乐和家庭传统之间寻找自己的梦想与归属。", "适合学习家庭关系、梦想和过去时叙事。", ["follow your dream", "remember someone"]), year: 2017, genre: "动画", durationMinutes: 105, url: "https://www.themoviedb.org/movie/354912" },
  { ...baseRecommendation("movie-020", "movie", "欢乐好声音", "Sing", "SING", "from-[#DDEFE4] to-[#B8DEC7]", "beginner", ["音乐", "成长"], "us", "一群普通人参加歌唱比赛，在练习和合作中建立自信。", "适合学习鼓励、准备和舞台表达。", ["give it a try", "believe in yourself"]), year: 2016, genre: "动画", durationMinutes: 108, url: "https://www.themoviedb.org/movie/335797" },
];

export const seriesRecommendations: SeriesRecommendation[] = [
  { ...baseRecommendation("series-001", "series", "老友记", "Friends", "FRIENDS", "from-[#E8E7F7] to-[#C9C8FA]", "beginner", ["喜剧", "日常生活"], "us", "六位朋友在纽约生活、工作和成长的经典情景喜剧。", "适合反复学习短句和口语搭配。", ["How are you doing?", "sounds good"]), genre: "喜剧", episodeMinutes: 22, seasons: 10, url: "https://www.imdb.com/title/tt0108778/" },
  { ...baseRecommendation("series-002", "series", "摩登家庭", "Modern Family", "FAMILY", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["喜剧", "日常生活"], "us", "三个彼此相关的家庭，用轻松幽默的方式面对生活琐事。", "适合学习真实生活中的语气和表达。", ["You know what?", "That makes sense"]), genre: "喜剧", episodeMinutes: 22, seasons: 11, url: "https://www.imdb.com/title/tt1442437/" },
  { ...baseRecommendation("series-003", "series", "唐顿庄园", "Downton Abbey", "DOWNTON", "from-[#F8EBD8] to-[#E9C995]", "advanced", ["剧情", "英式英语"], "uk", "英国贵族家庭与仆人在二十世纪初的生活故事。", "适合中高级学习者理解礼貌和正式语境。", ["if you don't mind", "quite right"]), genre: "剧情", episodeMinutes: 55, seasons: 6, url: "https://www.imdb.com/title/tt1606375/" },
  { ...baseRecommendation("series-004", "series", "硅谷", "Silicon Valley", "SILICON", "from-[#E4EDF5] to-[#B8D0E5]", "advanced", ["科技", "职场"], "us", "创业团队在科技行业中寻找产品和商业机会的喜剧。", "适合积累科技与职场词汇。", ["ship it", "move forward"]), genre: "喜剧", episodeMinutes: 28, seasons: 6, url: "https://www.imdb.com/title/tt2575988/" },
  { ...baseRecommendation("series-005", "series", "布里奇顿", "Bridgerton", "BRIDGERTON", "from-[#F7E5D5] to-[#F1C9A7]", "advanced", ["剧情", "英式英语"], "uk", "摄政时期伦敦社交季中的爱情、家庭和身份故事。", "适合挑战较丰富的词汇和正式语气。", ["I dare say", "how delightful"]), genre: "剧情", episodeMinutes: 58, seasons: 3, url: "https://www.imdb.com/title/tt8740790/" },
  { ...baseRecommendation("series-006", "series", "小谢尔顿", "Young Sheldon", "SHELDON", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["喜剧", "日常生活"], "us", "天才少年 Sheldon 在家庭和校园中成长的故事。", "适合学习日常叙事和表达观点。", ["I suppose", "that's the point"]), genre: "喜剧", episodeMinutes: 22, seasons: 7, url: "https://www.imdb.com/title/tt6226232/" },
  { ...baseRecommendation("series-007", "series", "办公室", "The Office", "THE OFFICE", "from-[#E8E7F7] to-[#C9C8FA]", "beginner", ["职场", "日常生活"], "us", "一群同事在办公室里处理工作、关系和各种日常尴尬。", "适合学习职场闲聊、会议和同事交流。", ["work together", "make small talk"]), genre: "喜剧", episodeMinutes: 22, seasons: 9, url: "https://www.themoviedb.org/tv/2316" },
  { ...baseRecommendation("series-008", "series", "神烦警探", "Brooklyn Nine-Nine", "BROOKLYN 99", "from-[#F7E5D5] to-[#F1C9A7]", "intermediate", ["职场", "喜剧"], "us", "布鲁克林警局的团队在案件、友情和办公室生活中不断合作。", "适合学习快速回应、玩笑和团队协作表达。", ["figure it out", "work as a team"]), genre: "喜剧", episodeMinutes: 22, seasons: 8, url: "https://www.themoviedb.org/tv/48891" },
  { ...baseRecommendation("series-009", "series", "善地", "The Good Place", "GOOD PLACE", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["生活", "观点"], "us", "几个性格不同的人在奇妙的环境中重新思考善良、选择和成长。", "适合学习观点、假设和道德话题表达。", ["make a choice", "become a better person"]), genre: "喜剧", episodeMinutes: 22, seasons: 4, url: "https://www.themoviedb.org/tv/66573" },
  { ...baseRecommendation("series-010", "series", "富家穷路", "Schitt's Creek", "SCHITT'S CREEK", "from-[#E4EDF5] to-[#B8D0E5]", "intermediate", ["家庭", "日常生活"], "us", "一个富裕家庭失去财富后，在小镇重新建立生活和关系。", "适合学习家庭对话、适应变化和幽默表达。", ["start over", "get used to"]), genre: "喜剧", episodeMinutes: 22, seasons: 6, url: "https://www.themoviedb.org/tv/61662" },
  { ...baseRecommendation("series-011", "series", "吉尔莫女孩", "Gilmore Girls", "GILMORE GIRLS", "from-[#E9E5FA] to-[#CEC5F1]", "intermediate", ["家庭", "校园"], "us", "母女二人在小镇生活中分享日常、学习、工作和成长。", "适合学习自然对话、家庭关系和快速回应。", ["keep in touch", "talk it over"]), genre: "剧情", episodeMinutes: 45, seasons: 7, url: "https://www.themoviedb.org/tv/4586" },
  { ...baseRecommendation("series-012", "series", "生活大爆炸", "The Big Bang Theory", "BIG BANG", "from-[#F8EBD8] to-[#E9C995]", "intermediate", ["日常生活", "科技"], "us", "一群朋友在工作、科学、友情和感情之间寻找平衡。", "适合学习朋友闲聊、观点和科技词汇。", ["make a point", "hang out"]), genre: "喜剧", episodeMinutes: 22, seasons: 12, url: "https://www.themoviedb.org/tv/1418" },
  { ...baseRecommendation("series-013", "series", "老爸老妈的浪漫史", "How I Met Your Mother", "HOW I MET", "from-[#E8E7F7] to-[#C9C8FA]", "intermediate", ["社交", "日常生活"], "us", "一群朋友在纽约经历约会、工作和友情中的各种变化。", "适合学习约会、讲故事和朋友间的口语。", ["go out", "tell a story"]), genre: "喜剧", episodeMinutes: 22, seasons: 9, url: "https://www.themoviedb.org/tv/1100" },
  { ...baseRecommendation("series-014", "series", "Ted Lasso", "Ted Lasso", "TED LASSO", "from-[#DDEFE4] to-[#B8DEC7]", "intermediate", ["职场", "励志"], "us", "一位乐观的教练进入陌生环境，用信任和幽默带领团队成长。", "适合学习鼓励、团队沟通和英美口音对比。", ["keep your spirits up", "build trust"]), genre: "喜剧", episodeMinutes: 30, seasons: 3, url: "https://www.themoviedb.org/tv/97546" },
  { ...baseRecommendation("series-015", "series", "小学风云", "Abbott Elementary", "ABBOTT", "from-[#F7E5D5] to-[#F1C9A7]", "intermediate", ["职场", "教育"], "us", "一群老师在资源有限的学校里合作解决教学与生活问题。", "适合学习工作沟通、建议和日常表达。", ["solve a problem", "work with others"]), genre: "喜剧", episodeMinutes: 22, seasons: 4, url: "https://www.themoviedb.org/tv/125935" },
  { ...baseRecommendation("series-016", "series", "好想做一次", "Never Have I Ever", "NEVER HAVE I EVER", "from-[#E4EDF5] to-[#B8D0E5]", "intermediate", ["校园", "家庭"], "us", "一名高中生在家庭、朋友、学业和自我认同之间成长。", "适合学习校园社交、情绪和表达愿望。", ["fit in", "figure things out"]), genre: "喜剧", episodeMinutes: 30, seasons: 4, url: "https://www.themoviedb.org/tv/100883" },
  { ...baseRecommendation("series-017", "series", "性爱自修室", "Sex Education", "SEX EDUCATION", "from-[#E9E5FA] to-[#CEC5F1]", "advanced", ["校园", "社交"], "uk", "学生们在校园和家庭关系中学习沟通、边界和成长。", "适合中高级学习者挑战英式口语与关系表达。", ["set a boundary", "talk honestly"]), genre: "喜剧", episodeMinutes: 50, seasons: 4, url: "https://www.themoviedb.org/tv/81356" },
  { ...baseRecommendation("series-018", "series", "王冠", "The Crown", "THE CROWN", "from-[#F8EBD8] to-[#E9C995]", "advanced", ["历史", "英式英语"], "uk", "围绕英国王室、责任与个人生活展开的历史剧。", "适合挑战正式表达、礼貌用语和英式发音。", ["take responsibility", "keep a promise"]), genre: "剧情", episodeMinutes: 55, seasons: 6, url: "https://www.themoviedb.org/tv/65494" },
  { ...baseRecommendation("series-019", "series", "金装律师", "Suits", "SUITS", "from-[#E8E7F7] to-[#C9C8FA]", "advanced", ["职场", "法律"], "us", "一家律师事务所中的合作、竞争和高压谈判不断推进故事。", "适合学习正式职场、谈判和表达立场。", ["make a case", "reach an agreement"]), genre: "剧情", episodeMinutes: 43, seasons: 9, url: "https://www.themoviedb.org/tv/37680" },
  { ...baseRecommendation("series-020", "series", "熊家餐馆", "The Bear", "THE BEAR", "from-[#DDEFE4] to-[#B8DEC7]", "advanced", ["职场", "家庭"], "us", "一位年轻厨师在高压厨房中面对工作、家庭和团队关系。", "适合挑战快速对白、职场冲突和情绪表达。", ["keep it together", "run a kitchen"]), genre: "剧情", episodeMinutes: 30, seasons: 4, url: "https://www.themoviedb.org/tv/136315" },
];

const recommendationPosterUrls: Record<string, string> = {
  "movie-001": "https://image.tmdb.org/t/p/w500/oAZXx2Zt8Ikrm3BpLMsXYHRabWM.jpg",
  "movie-002": "https://image.tmdb.org/t/p/w500/vxj2k0168d7K3pih7Aw6kqvvLcN.jpg",
  "movie-003": "https://image.tmdb.org/t/p/w500/1v1AZTI4QM2c6PYcm446RXDkZQu.jpg",
  "movie-004": "https://image.tmdb.org/t/p/w500/9H4jcc4GAgv1tPBMYEhl2rlP3pb.jpg",
  "movie-005": "https://image.tmdb.org/t/p/w500/vMURwcHmqCoWQHhJtMs8nTC2ij8.jpg",
  "movie-006": "https://image.tmdb.org/t/p/w500/cR2bQBza2KdQ8N1qXigzzbKNk9E.jpg",
  "series-001": "https://image.tmdb.org/t/p/w500/iDdFfZB5sexPhDOvacEhWWvgxel.jpg",
  "series-002": "https://image.tmdb.org/t/p/w500/7aR5985sE8CacO3yQMK5x57qLf3.jpg",
  "series-003": "https://image.tmdb.org/t/p/w500/u3Ow37NCmHAgRKUxyEBF9yCUloX.jpg",
  "series-004": "https://image.tmdb.org/t/p/w500/qpN9Sl35iNcOUTJdQYPObvdRQXt.jpg",
  "series-005": "https://image.tmdb.org/t/p/w500/jfA1G3guanPOFhwUzJsargpmB7F.jpg",
  "series-006": "https://image.tmdb.org/t/p/w500/n2sszgWewoknQjtN7DYgqWVIrlm.jpg",
  "movie-007": "https://image.tmdb.org/t/p/w500/76C6tTFrjibiLhTHgvPhVAQQ9nk.jpg",
  "movie-008": "https://image.tmdb.org/t/p/w500/pa5MteLxgMJ0FnY0E1nQdRN750i.jpg",
  "movie-009": "https://image.tmdb.org/t/p/w500/nAnzFcqORitpwvRQPceIt4mcm8G.jpg",
  "movie-010": "https://image.tmdb.org/t/p/w500/pplybKImR7LKzSVzRylK6Cl4dzm.jpg",
  "movie-011": "https://image.tmdb.org/t/p/w500/xUvcmKgDFRy79LqTibh7bpu1R5r.jpg",
  "movie-012": "https://image.tmdb.org/t/p/w500/oS5czlQL6oEH2MWS9DPjBMXSMc4.jpg",
  "movie-013": "https://image.tmdb.org/t/p/w500/tAAXqX7nTMPJtXCJUVC03EuiTK0.jpg",
  "movie-014": "https://image.tmdb.org/t/p/w500/8xtRXHmdaYp0LeddTf6pok34uiL.jpg",
  "movie-015": "https://image.tmdb.org/t/p/w500/szxBVXajhvjvOC4tbH6hygdumcs.jpg",
  "movie-016": "https://image.tmdb.org/t/p/w500/eHL3vjC6y8VJwx6FywTBK72Yh8Y.jpg",
  "movie-017": "https://image.tmdb.org/t/p/w500/tXAhMF48GYcmzhm45Iw4GDjNnB9.jpg",
  "movie-018": "https://image.tmdb.org/t/p/w500/gN3qUaxucFWNTBDsaxkyCQSbox2.jpg",
  "movie-019": "https://image.tmdb.org/t/p/w500/vtgPOrShQFkDm1PWY3TKrPmlS5i.jpg",
  "movie-020": "https://image.tmdb.org/t/p/w500/abJptbvY5UnAWkAf3eqeNHw1ESk.jpg",
  "series-007": "https://image.tmdb.org/t/p/w500/23kUb1firV8OS4r20StlOd6wTjf.jpg",
  "series-008": "https://image.tmdb.org/t/p/w500/eTw0aeKQp32u0440WYU5qH2DPoU.jpg",
  "series-009": "https://image.tmdb.org/t/p/w500/xrwrSQCrj0lqV6u7apSTdmVyw81.jpg",
  "series-010": "https://image.tmdb.org/t/p/w500/ihXe59qjw5hYqakeS6hAnuzsdlt.jpg",
  "series-011": "https://image.tmdb.org/t/p/w500/gwtzCwU2wdLLf8oejQu2TINiWfQ.jpg",
  "series-012": "https://image.tmdb.org/t/p/w500/9vVZDfKs5Iq8VuSKuyCZTIumdwa.jpg",
  "series-013": "https://image.tmdb.org/t/p/w500/pigfifd0UTyyqFteg4oylbg0XEw.jpg",
  "series-014": "https://image.tmdb.org/t/p/w500/uPtfFJmTKHCfYW2NTIND8SBeZBa.jpg",
  "series-015": "https://image.tmdb.org/t/p/w500/zjwJhHdgSUhBqDIHHOZkf53c2tb.jpg",
  "series-016": "https://image.tmdb.org/t/p/w500/ekl9strLu31QZDZiWFXdpDpOYpp.jpg",
  "series-017": "https://image.tmdb.org/t/p/w500/zvTQePeQPhP6jN7tspQz5HGv0ma.jpg",
  "series-018": "https://image.tmdb.org/t/p/w500/yndvBGfD2S09kv89uSCHQyDyYWy.jpg",
  "series-019": "https://image.tmdb.org/t/p/w500/53f5R3mleJZx5xmW0cIMQyXJGen.jpg",
  "series-020": "https://image.tmdb.org/t/p/w500/7y1ibpkTwlKYrxFbq3lh2RgIB1k.jpg",
};

export const recommendationData: EnglishRecommendation[] = [...speechRecommendations, ...movieRecommendations, ...seriesRecommendations].map((item) => {
  const posterUrl = recommendationPosterUrls[item.id];
  return posterUrl ? { ...item, posterUrl } : item;
});
