"use client";

import { BarChart3, Clock3, Medal, TrendingUp } from "lucide-react";
import { formatDuration } from "./ExerciseOverview";
import type { ExerciseStats } from "../types";

export function ExerciseStatistics({ stats }: { stats: ExerciseStats }) {
  const maxCount = Math.max(1, ...stats.weekTrend.map((item) => item.count));
  return <section className="rounded-[24px] border border-line bg-white p-6 shadow-card sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-bold text-[#4F9060]"><BarChart3 size={16} />基础统计</p><h2 className="mt-2 text-xl font-extrabold">看见自己的运动节奏</h2></div><TrendingUp className="text-[#4F9060]" size={22} /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat label="累计运动次数" value={String(stats.totalCount)} /><Stat label="总累计时长" value={formatDuration(stats.totalDuration)} /><Stat label="本月累计时长" value={formatDuration(stats.monthDuration)} /></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl bg-canvas p-4"><div className="flex items-center justify-between"><p className="text-sm font-bold">最近 6 周运动次数</p><span className="text-xs text-muted">按记录次数统计</span></div><div className="mt-5 flex h-36 items-end gap-2">{stats.weekTrend.map((item) => <div key={item.label} className="flex min-w-0 flex-1 flex-col items-center gap-2"><span className="text-xs font-bold text-[#4F9060]">{item.count}</span><div className="flex h-24 w-full items-end rounded-lg bg-white"><div className="w-full rounded-lg bg-[#A9D0AE] transition-all" style={{ height: (item.count / maxCount) * 100 + "%" }} /></div><span className="text-[10px] text-muted">{item.label}</span></div>)}</div></div><div className="rounded-2xl bg-canvas p-4"><p className="text-sm font-bold">运动类型占比</p><div className="mt-4 space-y-3">{stats.typeBreakdown.length ? stats.typeBreakdown.slice(0, 6).map((item) => <div key={item.typeId}><div className="flex items-center justify-between gap-3 text-xs"><span className="font-semibold">{item.icon} {item.name}</span><span className="text-muted">{item.count} 次 · {item.percentage}%</span></div><div className="mt-1.5 h-2 rounded-full bg-white"><div className="h-full rounded-full bg-[#8FBE96]" style={{ width: item.percentage + "%" }} /></div></div>) : <p className="py-5 text-sm text-muted">记录运动后，这里会显示类型分布。</p>}</div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-[#E5E9D7] bg-[#FBFCF5] p-4"><p className="flex items-center gap-2 text-xs font-bold text-[#8A7740]"><Medal size={15} />最常进行的运动</p><p className="mt-3 text-lg font-extrabold">{stats.mostFrequentType ? stats.mostFrequentType.icon + " " + stats.mostFrequentType.name : "暂无记录"}</p></div><div className="rounded-2xl border border-[#D9E8DB] bg-[#F7FBF7] p-4"><p className="flex items-center gap-2 text-xs font-bold text-[#4F9060]"><Clock3 size={15} />最近一次运动</p><p className="mt-3 text-lg font-extrabold">{stats.latestRecord ? stats.latestRecord.exerciseDate : "暂无记录"}</p></div></div></section>;
}

function Stat({ label, value }: { label: string; value: string }) {
  return <div className="rounded-2xl border border-line bg-canvas px-4 py-4"><p className="text-xs font-semibold text-muted">{label}</p><p className="mt-2 text-lg font-extrabold">{value}</p></div>;
}
