import * as React from "react";
import { Bookmark, BookmarkX, Check, LibraryBig } from "lucide-react";
import { wordStatusLabels, wordStatusTones } from "../logic/spacedRepetition";
import type { EnglishWord, WordProgress, WordStatus } from "../types";

export function VocabularyBook({ words, progress, onStatus, onFavorite, onRemove }: { words: EnglishWord[]; progress: Record<string, WordProgress>; onStatus: (wordId: string, status: WordStatus) => void; onFavorite: (wordId: string) => void; onRemove: (wordId: string) => void }) {
  const [view, setView] = React.useState<"vocabulary" | "favorites">("vocabulary");
  const [statusFilter, setStatusFilter] = React.useState<WordStatus | "all">("all");
  const list = words.filter((word) => { const item = progress[word.id]; if (!item) return false; const inView = view === "favorites" ? item.isFavorite : item.isInVocabularyBook && (item.status === "unknown" || item.status === "fuzzy"); const inStatus = statusFilter === "all" || item.status === statusFilter; return inView && inStatus; });

  return (
    <section className="rounded-[24px] border border-line bg-white p-6 shadow-card sm:p-8">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-semibold text-accent"><LibraryBig size={15} />生词本</div><h2 className="mt-2 text-xl font-extrabold">把需要再见几次的单词留下</h2></div><div className="flex rounded-xl bg-canvas p-1"><button onClick={() => setView("vocabulary")} className={`rounded-lg px-3 py-2 text-xs font-semibold ${view === "vocabulary" ? "bg-white text-ink shadow-sm" : "text-muted"}`}>全部生词</button><button onClick={() => setView("favorites")} className={`rounded-lg px-3 py-2 text-xs font-semibold ${view === "favorites" ? "bg-white text-ink shadow-sm" : "text-muted"}`}>我的收藏</button></div></div>
      <div className="mt-5 flex flex-wrap gap-2">{(["all", "unknown", "fuzzy", "known", "mastered"] as const).map((status) => <button key={status} onClick={() => setStatusFilter(status)} className={`rounded-xl px-3 py-2 text-xs font-semibold ${statusFilter === status ? "bg-ink text-white" : "bg-canvas text-muted hover:text-ink"}`}>{status === "all" ? "全部状态" : wordStatusLabels[status]}</button>)}</div>
      {list.length > 0 ? <div className="mt-6 space-y-3">{list.map((word) => { const item = progress[word.id]; if (!item) return null; return <div key={word.id} className="rounded-2xl border border-line px-4 py-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-sans font-bold">{word.word}</span><span className={`rounded-lg px-2 py-1 text-[11px] font-semibold ${wordStatusTones[item.status]}`}>{wordStatusLabels[item.status]}</span></div><p className="mt-1 text-sm text-muted">{word.meaningZh} · {word.topic}</p></div><div className="flex shrink-0 gap-1"><button onClick={() => onFavorite(word.id)} className="grid size-8 place-items-center rounded-lg text-muted hover:bg-canvas" aria-label={item.isFavorite ? "取消收藏" : "收藏单词"}><Bookmark size={15} fill={item.isFavorite ? "currentColor" : "none"} /></button>{view === "vocabulary" && <button onClick={() => onRemove(word.id)} className="grid size-8 place-items-center rounded-lg text-muted hover:bg-[#FFF0F1] hover:text-[#B75D6A]" aria-label="移出生词本"><BookmarkX size={15} /></button>}</div></div><div className="mt-4 flex flex-wrap gap-2">{(["unknown", "fuzzy", "known", "mastered"] as WordStatus[]).map((status) => <button key={status} onClick={() => onStatus(word.id, status)} className={`rounded-lg px-2.5 py-1.5 text-[11px] font-semibold ${item.status === status ? wordStatusTones[status] : "bg-canvas text-muted"}`}>{item.status === status && <Check size={12} className="mr-1 inline" />}{wordStatusLabels[status]}</button>)}</div></div>; })}</div> : <div className="mt-6 rounded-2xl border border-dashed border-[#D4D8DF] bg-canvas/40 px-5 py-10 text-center"><Bookmark className="mx-auto mb-3 text-muted" size={26} /><p className="font-semibold">这里还没有符合条件的单词</p><p className="mt-2 text-xs text-muted">标记“不认识”或“模糊”的单词，它们会自动进入生词本。</p></div>}
    </section>
  );
}

