import * as React from "react";
import { Gauge, Plus, Trash2 } from "lucide-react";
import { formatAmount } from "../calculations";
import type { BookkeepingBudget, BookkeepingCategory, MonthlySummary } from "../types";

export function BudgetManager({ month, budgets, categories, summary, onChange }: { month: string; budgets: BookkeepingBudget[]; categories: BookkeepingCategory[]; summary: MonthlySummary; onChange: (budgets: BookkeepingBudget[]) => void }) {
  const [amount, setAmount] = React.useState(""); const [categoryId, setCategoryId] = React.useState(""); const active = budgets.filter((item) => item.month === month && item.isActive); const totalBudgetItem = active.find((item) => !item.categoryId); const totalBudget = active.filter((item) => !item.categoryId).reduce((sum, item) => sum + item.amount, 0); const categoryBudgets = active.filter((item) => item.categoryId);
  const save = () => { const numeric = Number(amount); if (!numeric || numeric <= 0) return; const id = `budget-${month}-${categoryId || "total"}`; const next = budgets.filter((item) => item.id !== id); onChange([...next, { id, month, amount: numeric, categoryId: categoryId || undefined, isActive: true, updatedAt: new Date().toISOString() }]); setAmount(""); };
  return <section className="rounded-[28px] border border-line bg-white p-6 shadow-card sm:p-8"><p className="flex items-center gap-2 text-sm font-bold text-accent"><Gauge size={16} />预算管理</p><h2 className="mt-2 text-xl font-extrabold">给本月支出一个温和边界</h2><div className="mt-5 grid gap-5 xl:grid-cols-[280px_1fr]"><div className="rounded-2xl bg-canvas p-4"><p className="text-sm font-bold">设置 {month} 预算</p><input type="number" min="0" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="预算金额" className="mt-3 w-full rounded-xl border border-line bg-white px-3 py-2.5 text-sm outline-none" /><select value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="mt-3 w-full rounded-xl border border-line bg-white px-3 py-2.5 text-sm text-muted outline-none"><option value="">整月预算</option>{categories.filter((item) => item.type === "expense" && item.isActive).map((item) => <option key={item.id} value={item.id}>{item.icon} {item.name}</option>)}</select><button type="button" onClick={save} disabled={!amount || Number(amount) <= 0} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-ink px-3 py-2.5 text-sm font-bold text-white disabled:opacity-40"><Plus size={15} />保存预算</button></div><div><div className="rounded-2xl border border-line p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold">整月支出预算</p><p className="mt-1 text-xs text-muted">已使用 {formatAmount(summary.expense)} / {formatAmount(totalBudget)}</p></div><div className="flex items-center gap-3"><p className="text-lg font-extrabold">{totalBudget ? `${Math.min(100, Math.round((summary.expense / totalBudget) * 100))}%` : "未设置"}</p>{totalBudgetItem && <button type="button" onClick={() => onChange(budgets.filter((item) => item.id !== totalBudgetItem.id))} className="text-muted hover:text-[#A95151]" aria-label="删除月度预算"><Trash2 size={15} /></button>}</div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#EEEAFB]"><div className="h-full rounded-full bg-[#7567B6] transition-all" style={{ width: `${totalBudget ? Math.min(100, (summary.expense / totalBudget) * 100) : 0}%` }} /></div></div><div className="mt-3 space-y-2">{categoryBudgets.map((budget) => <div key={budget.id} className="flex items-center gap-3 rounded-xl border border-line px-4 py-3 text-sm"><span className="flex-1">{categories.find((item) => item.id === budget.categoryId)?.name ?? "分类预算"}</span><span className="font-bold">{formatAmount(budget.amount)}</span><button type="button" onClick={() => onChange(budgets.filter((item) => item.id !== budget.id))} className="text-muted hover:text-[#A95151]" aria-label="删除预算"><Trash2 size={15} /></button></div>)}{categoryBudgets.length === 0 && <p className="rounded-xl bg-canvas p-4 text-sm text-muted">还没有分类预算，可以从左侧添加。</p>}</div></div></div></section>;
}
