import * as React from "react";
import { CalendarRange, Search } from "lucide-react";
import type { BookkeepingAccount, BookkeepingCategory, BookkeepingRecord, RecordType } from "../types";
import { RecordList } from "./RecordList";

export function History({ records, categories, accounts, onEdit, onDelete }: { records: BookkeepingRecord[]; categories: BookkeepingCategory[]; accounts: BookkeepingAccount[]; onEdit: (record: BookkeepingRecord) => void; onDelete: (id: string) => void }) {
  const [month, setMonth] = React.useState(""); const [type, setType] = React.useState<RecordType | "all">("all"); const [category, setCategory] = React.useState("all"); const [account, setAccount] = React.useState("all"); const [query, setQuery] = React.useState("");
  const filtered = records.filter((record) => (!month || record.date.startsWith(month)) && (type === "all" || record.type === type) && (category === "all" || record.categoryId === category) && (account === "all" || record.accountId === account) && (!query || record.note.includes(query) || (categories.find((item) => item.id === record.categoryId)?.name ?? "").includes(query))).sort((a, b) => `${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`));
  return <section className="rounded-[28px] border border-line bg-white p-6 shadow-card sm:p-8"><div><p className="flex items-center gap-2 text-sm font-bold text-accent"><CalendarRange size={16} />历史账单</p><h2 className="mt-2 text-xl font-extrabold">按条件查找过去的记录</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="rounded-xl border border-line bg-canvas px-3 py-2.5 text-sm text-muted outline-none" /><select value={type} onChange={(event) => setType(event.target.value as RecordType | "all")} className="rounded-xl border border-line bg-canvas px-3 py-2.5 text-sm text-muted outline-none"><option value="all">全部类型</option><option value="income">收入</option><option value="expense">支出</option></select><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-xl border border-line bg-canvas px-3 py-2.5 text-sm text-muted outline-none"><option value="all">全部分类</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={account} onChange={(event) => setAccount(event.target.value)} className="rounded-xl border border-line bg-canvas px-3 py-2.5 text-sm text-muted outline-none"><option value="all">全部账户</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="flex items-center gap-2 rounded-xl border border-line bg-canvas px-3"><Search size={15} className="text-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索备注" className="min-w-0 flex-1 bg-transparent py-2.5 text-sm outline-none" /></label></div><p className="mt-4 text-xs text-muted">找到 {filtered.length} 笔账单</p><div className="mt-4"><RecordList records={filtered} categories={categories} accounts={accounts} emptyText="没有符合条件的账单。" onEdit={onEdit} onDelete={onDelete} /></div></section>;
}
