import * as React from "react";
import { Download, FileJson, FileSpreadsheet, RotateCcw, Upload } from "lucide-react";
import type { BookkeepingAccount, BookkeepingCategory, BookkeepingRecord, BookkeepingState, BookkeepingBudget } from "../types";
import { validateBookkeepingPayload } from "../storage";

interface ImportExportProps { state: BookkeepingState; categories: BookkeepingCategory[]; accounts: BookkeepingAccount[]; onImport: (state: BookkeepingState) => void; onNotice: (message: string) => void; }

function download(content: string, filename: string, type: string) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }
function csvValue(value: string | number): string { const text = String(value).replace(/"/g, '""'); return `"${text}"`; }

export function ImportExport({ state, categories, accounts, onImport, onNotice }: ImportExportProps) {
  const inputRef = React.useRef<HTMLInputElement>(null);
  const exportJson = () => download(JSON.stringify(state, null, 2), `nova-记账本-${new Date().toISOString().slice(0, 10)}.json`, "application/json;charset=utf-8");
  const exportCsv = () => { const header = ["类型", "金额", "分类", "账户", "日期", "时间", "备注"]; const rows = state.records.map((record: BookkeepingRecord) => [record.type === "income" ? "收入" : "支出", record.amount, categories.find((item) => item.id === record.categoryId)?.name ?? "未分类", accounts.find((item) => item.id === record.accountId)?.name ?? "未知账户", record.date, record.time, record.note]); download(`\uFEFF${[header, ...rows].map((row) => row.map((value) => csvValue(value)).join(",")).join("\n")}`, `nova-记账本-${new Date().toISOString().slice(0, 10)}.csv`, "text/csv;charset=utf-8"); };
  const handleFile = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed: unknown = JSON.parse(String(reader.result ?? "")); const result = validateBookkeepingPayload(parsed); if (!result.valid) { onNotice(result.message); return; } if (!window.confirm(`即将覆盖当前 ${state.records.length} 笔账单、分类、账户和预算数据，确定继续吗？`)) return; onImport(result.payload); onNotice("JSON 数据导入成功"); } catch { onNotice("无法读取这个 JSON 文件，请检查文件格式。"); } finally { event.target.value = ""; } }; reader.readAsText(file); };
  return <section className="rounded-[28px] border border-line bg-white p-6 shadow-card sm:p-8"><p className="flex items-center gap-2 text-sm font-bold text-accent"><RotateCcw size={16} />数据管理</p><h2 className="mt-2 text-xl font-extrabold">把账本安全地带走</h2><p className="mt-2 text-sm leading-6 text-muted">导入前会校验结构，覆盖现有数据前会再次确认。</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><button type="button" onClick={exportJson} className="inline-flex items-center justify-center gap-2 rounded-xl border border-line bg-canvas px-4 py-3 text-sm font-bold text-muted hover:text-ink"><FileJson size={16} />导出 JSON</button><button type="button" onClick={exportCsv} className="inline-flex items-center justify-center gap-2 rounded-xl border border-line bg-canvas px-4 py-3 text-sm font-bold text-muted hover:text-ink"><FileSpreadsheet size={16} />导出 CSV</button><button type="button" onClick={() => inputRef.current?.click()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-bold text-white hover:opacity-90"><Upload size={16} />导入 JSON</button></div><input ref={inputRef} type="file" accept="application/json,.json" onChange={handleFile} className="hidden" /><p className="mt-4 flex items-center gap-2 text-xs text-muted"><Download size={13} />CSV 包含类型、金额、分类、账户、日期、时间和备注字段。</p></section>;
}
