import type { NewsCategory, NewsSource } from "./types";

const now = "2026-08-05T00:00:00.000Z";

export const DEFAULT_NEWS_SOURCES: NewsSource[] = [
  {
    id: "gdelt",
    name: "GDELT 全球新闻数据",
    domain: "gdeltproject.org",
    sourceType: "gdelt",
    language: "多语言",
    countryOrRegion: "全球",
    categories: ["推荐", "国内", "国际", "时政", "社会", "财经", "科技", "体育", "环境", "军事"],
    homepageUrl: "https://www.gdeltproject.org/",
    isEnabled: true,
    reliabilityNote: "公开新闻研究数据源，适合跨来源检索和事件发现。",
    usageNote: "仅展示标题、摘要、来源和原文链接，不复制完整正文。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cns-scroll-rss",
    name: "中新网即时 RSS",
    domain: "chinanews.com.cn",
    sourceType: "official-rss",
    language: "中文",
    countryOrRegion: "中国",
    categories: ["推荐", "国内", "时政", "社会"],
    rssUrl: "https://www.chinanews.com.cn/rss/scroll-news.xml",
    homepageUrl: "https://www.chinanews.com/rss/index.shtml",
    isEnabled: true,
    reliabilityNote: "中新网公开 RSS，提供即时新闻订阅。",
    usageNote: "按中新网 RSS 页面授权说明使用，仅保存标题、摘要、来源、时间和原文链接。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cns-china-rss",
    name: "中新网国内与时政 RSS",
    domain: "chinanews.com.cn",
    sourceType: "official-rss",
    language: "中文",
    countryOrRegion: "中国",
    categories: ["国内", "时政", "社会"],
    rssUrl: "https://www.chinanews.com.cn/rss/china.xml",
    homepageUrl: "https://www.chinanews.com/rss/index.shtml",
    isEnabled: true,
    reliabilityNote: "中新网公开 RSS，覆盖国内与时政新闻。",
    usageNote: "按中新网 RSS 页面授权说明使用，不保存完整正文。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cns-world-rss",
    name: "中新网国际 RSS",
    domain: "chinanews.com.cn",
    sourceType: "official-rss",
    language: "中文",
    countryOrRegion: "全球",
    categories: ["国际"],
    rssUrl: "https://www.chinanews.com.cn/rss/world.xml",
    homepageUrl: "https://www.chinanews.com/rss/index.shtml",
    isEnabled: true,
    reliabilityNote: "中新网公开 RSS，覆盖国际新闻。",
    usageNote: "按中新网 RSS 页面授权说明使用，不保存完整正文。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cns-sports-rss",
    name: "中新网体育 RSS",
    domain: "chinanews.com.cn",
    sourceType: "official-rss",
    language: "中文",
    countryOrRegion: "中国 / 全球",
    categories: ["体育"],
    rssUrl: "https://www.chinanews.com.cn/rss/sports.xml",
    homepageUrl: "https://www.chinanews.com/rss/index.shtml",
    isEnabled: true,
    reliabilityNote: "中新网公开 RSS，覆盖体育新闻。",
    usageNote: "按中新网 RSS 页面授权说明使用，不保存完整正文。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cns-finance-rss",
    name: "中新网财经 RSS",
    domain: "chinanews.com.cn",
    sourceType: "official-rss",
    language: "中文",
    countryOrRegion: "中国",
    categories: ["财经"],
    rssUrl: "https://www.chinanews.com.cn/rss/finance.xml",
    homepageUrl: "https://www.chinanews.com/rss/index.shtml",
    isEnabled: true,
    reliabilityNote: "中新网公开 RSS，覆盖财经新闻。",
    usageNote: "按中新网 RSS 页面授权说明使用，不保存完整正文。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cns-culture-rss",
    name: "中新网文娱 RSS",
    domain: "chinanews.com.cn",
    sourceType: "official-rss",
    language: "中文",
    countryOrRegion: "中国 / 全球",
    categories: ["娱乐", "文化"],
    rssUrl: "https://www.chinanews.com.cn/rss/culture.xml",
    homepageUrl: "https://www.chinanews.com/rss/index.shtml",
    isEnabled: true,
    reliabilityNote: "中新网公开 RSS，覆盖文娱新闻。",
    usageNote: "按中新网 RSS 页面授权说明使用，不保存完整正文。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bbc-technology-rss",
    name: "BBC Technology RSS",
    domain: "bbc.co.uk",
    sourceType: "official-rss",
    language: "English",
    countryOrRegion: "英国 / 全球",
    categories: ["科技"],
    rssUrl: "https://feeds.bbci.co.uk/news/technology/rss.xml",
    homepageUrl: "https://www.bbc.com/news/technology",
    isEnabled: true,
    reliabilityNote: "BBC Technology 官方 RSS，用于补充科技新闻覆盖。",
    usageNote: "遵循 BBC RSS 使用条款，仅展示标题、摘要、来源、时间和原文链接。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cdc-weekly-rss",
    name: "中国疾控中心周报 RSS",
    domain: "chinacdc.cn",
    sourceType: "official-rss",
    language: "English",
    countryOrRegion: "中国",
    categories: ["健康"],
    rssUrl: "https://weekly.chinacdc.cn/rss/current.xml",
    homepageUrl: "https://weekly.chinacdc.cn/showRssInfo.htm",
    isEnabled: true,
    reliabilityNote: "中国疾控中心官方英文周报 RSS，偏公共卫生和科研信息。",
    usageNote: "仅保存 RSS 提供的标题、摘要、时间和链接，不保存完整正文。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bbc-health-rss",
    name: "BBC Health RSS",
    domain: "bbc.co.uk",
    sourceType: "official-rss",
    language: "English",
    countryOrRegion: "英国 / 全球",
    categories: ["健康"],
    rssUrl: "https://feeds.bbci.co.uk/news/health/rss.xml",
    homepageUrl: "https://www.bbc.com/news/health",
    isEnabled: true,
    reliabilityNote: "BBC Health 官方 RSS，用于补充健康新闻覆盖。",
    usageNote: "遵循 BBC RSS 使用条款，仅展示标题、摘要、来源、时间和原文链接。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "guardian-education-rss",
    name: "The Guardian Education RSS",
    domain: "theguardian.com",
    sourceType: "official-rss",
    language: "English",
    countryOrRegion: "英国 / 全球",
    categories: ["教育"],
    rssUrl: "https://www.theguardian.com/education/rss",
    homepageUrl: "https://www.theguardian.com/education",
    isEnabled: true,
    reliabilityNote: "The Guardian Education 公开 RSS，用于补充教育新闻覆盖。",
    usageNote: "仅用于个人非商业阅读场景，遵循 Guardian RSS 使用条款。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "unesco-unevoc-rss",
    name: "UNESCO-UNEVOC News RSS",
    domain: "unesco.org",
    sourceType: "official-rss",
    language: "English",
    countryOrRegion: "联合国教科文组织 / 全球",
    categories: ["教育"],
    rssUrl: "https://connect.unevoc.unesco.org/unevoc_news.xml",
    homepageUrl: "https://connect.unevoc.unesco.org/home/rss-feed",
    isEnabled: true,
    reliabilityNote: "UNESCO-UNEVOC 官方教育与职业教育新闻 RSS。",
    usageNote: "仅展示 RSS 摘要信息和原文链接，遵循 UNESCO 内容使用要求。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bbc-science-environment-rss",
    name: "BBC Science & Environment RSS",
    domain: "bbc.co.uk",
    sourceType: "official-rss",
    language: "English",
    countryOrRegion: "英国 / 全球",
    categories: ["环境"],
    rssUrl: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    homepageUrl: "https://www.bbc.com/news/science_and_environment",
    isEnabled: true,
    reliabilityNote: "BBC Science & Environment 官方 RSS，用于补充环境新闻覆盖。",
    usageNote: "遵循 BBC RSS 使用条款，仅展示标题、摘要、来源、时间和原文链接。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "guardian-environment-rss",
    name: "The Guardian Environment RSS",
    domain: "theguardian.com",
    sourceType: "official-rss",
    language: "English",
    countryOrRegion: "英国 / 全球",
    categories: ["环境"],
    rssUrl: "https://www.theguardian.com/environment/rss",
    homepageUrl: "https://www.theguardian.com/environment",
    isEnabled: true,
    reliabilityNote: "The Guardian Environment 公开 RSS，用于补充环境新闻覆盖。",
    usageNote: "仅用于个人非商业阅读场景，遵循 Guardian RSS 使用条款。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "us-army-rss",
    name: "U.S. Army RSS",
    domain: "army.mil",
    sourceType: "official-rss",
    language: "English",
    countryOrRegion: "美国",
    categories: ["军事"],
    rssUrl: "https://www.army.mil/rss/static/1.xml",
    homepageUrl: "https://www.army.mil/",
    isEnabled: true,
    reliabilityNote: "美国陆军官方 RSS，代表官方发布口径，不等同于完整军事新闻覆盖。",
    usageNote: "仅展示官方 RSS 提供的标题、摘要、来源、时间和原文链接。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bbc-general-rss",
    name: "BBC News RSS",
    domain: "bbc.co.uk",
    sourceType: "official-rss",
    language: "English",
    countryOrRegion: "英国 / 全球",
    categories: ["其他"],
    rssUrl: "https://feeds.bbci.co.uk/news/rss.xml",
    homepageUrl: "https://www.bbc.com/news",
    isEnabled: true,
    reliabilityNote: "BBC News 综合官方 RSS，用于补充其它分类。",
    usageNote: "遵循 BBC RSS 使用条款，仅展示标题、摘要、来源、时间和原文链接。",
    createdAt: now,
    updatedAt: now,
  },
];

export const CATEGORY_QUERIES: Record<NewsCategory, string> = {
  推荐: "(world OR China OR economy OR technology OR sports OR health)",
  国内: "(China OR 中国 OR 国内)",
  国际: "(world OR international OR 国际 OR global)",
  时政: "(politics OR government OR election OR 政策 OR 政治)",
  社会: "(society OR social OR 社会 OR public)",
  财经: "(economy OR finance OR business OR market OR 财经 OR 经济)",
  科技: "(technology OR science OR AI OR 科技 OR 科学)",
  体育: "(sports OR football OR basketball OR 体育 OR 足球 OR 篮球)",
  文化: "(culture OR art OR 文化 OR 艺术)",
  娱乐: "(entertainment OR film OR music OR 娱乐 OR 电影)",
  健康: "(health OR medicine OR 健康 OR 医疗)",
  教育: "(education OR school OR 教育 OR 学校)",
  环境: "(climate OR environment OR 环境 OR 气候)",
  军事: "(military OR defense OR conflict OR 军事 OR 国防)",
  其他: "(news OR 新闻)",
};

export function getSourceById(id: string, sources: NewsSource[] = DEFAULT_NEWS_SOURCES): NewsSource | undefined {
  return sources.find((source) => source.id === id);
}

export function getOfficialRssSources(category: NewsCategory, sources: NewsSource[] = DEFAULT_NEWS_SOURCES): NewsSource[] {
  return sources.filter((source) => source.sourceType === "official-rss" && source.isEnabled && source.categories.includes(category));
}
