"use client";

import * as React from "react";
import { Check, ChevronDown, ChevronUp, CircleAlert, Lightbulb, MessageCircle, Play, RotateCcw, Square, Volume2 } from "lucide-react";
import type { SavedExpression, SpeakingMessage, SpeakingScenario, SpeakingSettings } from "../types";
import { formatDuration } from "../utils";
import { SpeakingInput } from "./SpeakingInput";

export function ConversationPanel({ scenario, messages, settings, elapsedSeconds, hint, onHint, onSend, onEnd, input, onInputChange, onSpeak, isSpeaking, isSending, error, onRetry, onSaveExpression, savedExpressions, voiceStatus, voiceError, onVoice }: { scenario: SpeakingScenario; messages: SpeakingMessage[]; settings: SpeakingSettings; elapsedSeconds: number; hint: string; onHint: () => void; onSend: () => void; onEnd: () => void; input: string; onInputChange: (value: string) => void; onSpeak: (text: string) => void; isSpeaking: boolean; isSending: boolean; error: string; onRetry: () => void; onSaveExpression: (message: SpeakingMessage) => void; savedExpressions: SavedExpression[]; voiceStatus: "idle" | "listening" | "error"; voiceError: string; onVoice: () => void }) {
  const [openFeedback, setOpenFeedback] = React.useState<Record<string, boolean>>({});
  return <section className="overflow-hidden rounded-[28px] border border-line bg-white shadow-card"><header className="flex flex-col gap-4 border-b border-line bg-[#F7F7FB] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><div className="flex flex-wrap items-center gap-2 text-xs font-semibold text-accent"><MessageCircle size={15} />{scenario.titleZh}<span className="rounded-lg bg-white px-2 py-1 text-muted">{scenario.titleEn}</span></div><p className="mt-2 text-sm text-muted">AI：{scenario.aiRole} · 你：{scenario.userRole}</p></div><div className="flex items-center gap-3"><div className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-muted">第 {messages.filter((message) => message.role === "user").length} 轮 · {formatDuration(elapsedSeconds)}</div><button type="button" onClick={onEnd} className="inline-flex items-center gap-2 rounded-xl bg-ink px-3 py-2 text-xs font-bold text-white transition hover:-translate-y-0.5"><Square size={13} fill="currentColor" />结束练习</button></div></header><div className="max-h-[560px] space-y-5 overflow-y-auto px-4 py-5 sm:px-7 sm:py-7">{messages.map((message) => <MessageBubble key={message.id} message={message} settings={settings} onSpeak={onSpeak} isSpeaking={isSpeaking} isFeedbackOpen={openFeedback[message.id] ?? settings.showFeedback} onToggleFeedback={() => setOpenFeedback((current) => ({ ...current, [message.id]: !(current[message.id] ?? settings.showFeedback) }))} onSaveExpression={onSaveExpression} isSaved={savedExpressions.some((expression) => expression.id === `expression-${message.id}`)} />)}{isSending && <div className="flex items-center gap-3 text-sm text-muted"><div className="grid size-9 place-items-center rounded-full bg-[#E7E9FF] text-accent"><MessageCircle size={16} /></div><span>AI 正在组织回复…</span></div>}{error && <div className="flex items-center justify-between gap-3 rounded-2xl border border-[#F0D2BB] bg-[#FFF8F2] px-4 py-3 text-sm text-[#9C5D32]"><span className="flex items-center gap-2"><CircleAlert size={16} />{error}</span><button type="button" onClick={onRetry} className="inline-flex shrink-0 items-center gap-1 font-semibold"><RotateCcw size={14} />重试</button></div>}</div><div className="border-t border-line bg-[#FCFCFD] px-4 py-3 sm:px-7"><div className="flex flex-wrap items-center justify-between gap-2"><button type="button" onClick={onHint} className="inline-flex items-center gap-2 rounded-xl bg-[#F0F0FF] px-3 py-2 text-xs font-semibold text-accent transition hover:bg-[#E7E6FF]"><Lightbulb size={14} />给我一个提示</button>{hint && <p className="text-xs text-muted">{hint}</p>}</div></div><SpeakingInput value={input} onChange={onInputChange} onSend={onSend} onVoice={onVoice} voiceStatus={voiceStatus} voiceError={voiceError} disabled={isSending} /></section>;
}

function MessageBubble({ message, settings, onSpeak, isSpeaking, isFeedbackOpen, onToggleFeedback, onSaveExpression, isSaved }: { message: SpeakingMessage; settings: SpeakingSettings; onSpeak: (text: string) => void; isSpeaking: boolean; isFeedbackOpen: boolean; onToggleFeedback: () => void; onSaveExpression: (message: SpeakingMessage) => void; isSaved: boolean }) {
  const isAi = message.role === "ai";
  return <div className={`flex gap-3 ${isAi ? "justify-start" : "justify-end"}`}><div className={`max-w-[min(86%,680px)] ${isAi ? "order-2" : "order-1"}`}><div className={`rounded-2xl px-4 py-3 ${isAi ? "rounded-tl-md bg-[#F3F3FF]" : "rounded-tr-md bg-ink text-white"}`}><p className="text-sm leading-7">{message.text}</p>{isAi && settings.showTranslation && message.translation && <p className="mt-2 border-t border-accent/10 pt-2 text-xs leading-5 text-muted">{message.translation}</p>}</div>{isAi ? <div className="mt-2 flex items-center gap-2"><button type="button" onClick={() => onSpeak(message.text)} className="inline-flex items-center gap-1 rounded-lg px-2 py-1 text-[11px] font-semibold text-muted hover:bg-canvas hover:text-accent"><Volume2 size={13} />{isSpeaking ? "停止朗读" : "朗读"}</button></div> : message.feedback && <div className="mt-2 rounded-xl border border-line bg-white p-3"><div className="flex items-center justify-between gap-2"><p className="flex items-center gap-1.5 text-xs font-semibold text-muted"><Check size={14} className={message.feedback.clear ? "text-[#43845D]" : "text-[#B26F3C]"} />{message.feedback.clear ? "表达基本清楚" : "可以再展开一点"}</p><button type="button" onClick={onToggleFeedback} className="inline-flex items-center gap-1 text-[11px] font-semibold text-accent">{isFeedbackOpen ? "收起反馈" : "查看反馈"}{isFeedbackOpen ? <ChevronUp size={13} /> : <ChevronDown size={13} />}</button></div>{isFeedbackOpen && <div className="mt-3 space-y-3 text-xs leading-5"><div><p className="font-semibold text-muted">更自然的表达</p><p className="mt-1 font-semibold text-ink">{message.feedback.naturalVersion}</p></div>{message.feedback.grammarIssues.length > 0 && <div><p className="font-semibold text-muted">重点提醒</p><p className="mt-1 text-[#9C5D32]">{message.feedback.grammarIssues.join(" ")}</p></div>}<p className="text-muted">{message.feedback.explanation}</p><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => onSpeak(message.feedback?.naturalVersion ?? "")} className="inline-flex items-center gap-1 rounded-lg bg-canvas px-2 py-1 font-semibold text-muted hover:text-accent"><Play size={12} />朗读建议</button><button type="button" onClick={() => onSaveExpression(message)} className="inline-flex items-center gap-1 rounded-lg bg-canvas px-2 py-1 font-semibold text-muted hover:text-accent">{isSaved ? <Check size={12} /> : <Lightbulb size={12} />}{isSaved ? "已收藏表达" : "收藏表达"}</button></div></div>}</div>}</div><div className={`grid size-9 shrink-0 place-items-center rounded-full text-xs font-bold ${isAi ? "order-1 bg-[#E7E9FF] text-accent" : "order-2 bg-[#F0E8DD] text-[#8A6C49]"}`}>{isAi ? "AI" : "我"}</div></div>;
}
