"use client";

import * as React from "react";
import { Check, Copy, Heart, Volume2 } from "lucide-react";
import type { SavedExpression, SpeakingScenario } from "../types";

export function SavedExpressions({ expressions, scenarios, onRemove, onCopy, onSpeak }: { expressions: SavedExpression[]; scenarios: SpeakingScenario[]; onRemove: (id: string) => void; onCopy: (text: string) => void; onSpeak: (text: string) => void }) {
  const [filter, setFilter] = React.useState("all");
  const [copied, setCopied] = React.useState("");
  const filtered = expressions.filter((expression) => filter === "all" || expression.scenarioId === filter);
  const copy = (expression: SavedExpression) => { onCopy(expression.expression); setCopied(expression.id); window.setTimeout(() => setCopied(""), 1200); };
  return <section className="rounded-[28px] border border-line bg-white p-6 shadow-card sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="flex items-center gap-2 text-sm font-semibold text-accent"><Heart size={16} />我的表达</p><h2 className="mt-2 text-xl font-extrabold">收藏值得重复使用的句子</h2></div><select value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-xl border border-line bg-white px-3 py-2 text-xs font-semibold text-muted outline-none"><option value="all">全部场景</option>{scenarios.map((scenario) => <option key={scenario.id} value={scenario.id}>{scenario.titleZh}</option>)}</select></div>{filtered.length === 0 ? <div className="mt-6 rounded-2xl border border-dashed border-[#D4D8DF] bg-canvas/40 px-5 py-10 text-center text-sm text-muted">在对话反馈中收藏表达，它们会集中显示在这里。</div> : <div className="mt-6 grid gap-3 md:grid-cols-2">{filtered.map((expression) => <article key={expression.id} className="rounded-2xl border border-line bg-canvas/50 p-4"><p className="font-semibold leading-6">{expression.expression}</p><p className="mt-2 text-xs leading-5 text-muted">{expression.explanation}</p><div className="mt-4 flex items-center justify-between gap-2"><span className="text-[11px] font-semibold text-muted">来自：{expression.scenarioTitle}</span><div className="flex items-center gap-1"><button type="button" onClick={() => onSpeak(expression.expression)} className="grid size-8 place-items-center rounded-lg bg-white text-muted hover:text-accent" aria-label="朗读表达"><Volume2 size={14} /></button><button type="button" onClick={() => copy(expression)} className="grid size-8 place-items-center rounded-lg bg-white text-muted hover:text-accent" aria-label="复制表达">{copied === expression.id ? <Check size={14} /> : <Copy size={14} />}</button><button type="button" onClick={() => onRemove(expression.id)} className="px-2 text-xs font-semibold text-muted hover:text-[#B26F3C]">取消收藏</button></div></div></article>)}</div>}</section>;
}
