"use client";

import * as React from "react";
import { ChevronDown, ChevronUp, History, Trash2 } from "lucide-react";
import type { SpeakingScenario, SpeakingSessionRecord } from "../types";
import { difficultyLabels } from "../scenarios";
import { formatDateLabel, formatDuration } from "../utils";

export function SpeakingHistory({ sessions, scenarios, onDelete, onClear }: { sessions: SpeakingSessionRecord[]; scenarios: SpeakingScenario[]; onDelete: (id: string) => void; onClear: () => void }) {
  const [filter, setFilter] = React.useState("all");
  const [expanded, setExpanded] = React.useState<string | null>(null);
  const filtered = sessions.filter((session) => filter === "all" || session.scenarioId === filter).slice(0, 8);
  return <section className="rounded-[28px] border border-line bg-white p-6 shadow-card sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="flex items-center gap-2 text-sm font-semibold text-accent"><History size={16} />历史练习</p><h2 className="mt-2 text-xl font-extrabold">把每次开口都留下来</h2></div><div className="flex items-center gap-2"><select value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-xl border border-line bg-white px-3 py-2 text-xs font-semibold text-muted outline-none"><option value="all">全部场景</option>{scenarios.map((scenario) => <option key={scenario.id} value={scenario.id}>{scenario.titleZh}</option>)}</select>{sessions.length > 0 && <button type="button" onClick={onClear} className="inline-flex items-center gap-1 rounded-xl bg-canvas px-3 py-2 text-xs font-semibold text-muted hover:text-[#B26F3C]"><Trash2 size={13} />清空</button>}</div></div>{filtered.length === 0 ? <div className="mt-6 rounded-2xl border border-dashed border-[#D4D8DF] bg-canvas/40 px-5 py-10 text-center text-sm text-muted">完成一次练习后，历史记录会显示在这里。</div> : <div className="mt-6 space-y-3">{filtered.map((session) => <article key={session.id} className="rounded-2xl border border-line bg-white p-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-[#F0F0FF] text-accent"><History size={16} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{session.scenarioTitle}</h3><span className="rounded-lg bg-canvas px-2 py-1 text-[11px] font-semibold text-muted">{difficultyLabels[session.difficulty]}</span></div><p className="mt-1 text-xs text-muted">{formatDateLabel(session.date)} · {formatDuration(session.durationSeconds)} · {session.turnCount} 轮</p></div><button type="button" onClick={() => setExpanded(expanded === session.id ? null : session.id)} className="grid size-8 place-items-center rounded-lg bg-canvas text-muted hover:text-accent" aria-label={expanded === session.id ? "收起详情" : "查看详情"}>{expanded === session.id ? <ChevronUp size={15} /> : <ChevronDown size={15} />}</button><button type="button" onClick={() => onDelete(session.id)} className="grid size-8 place-items-center rounded-lg bg-canvas text-muted hover:text-[#B26F3C]" aria-label="删除练习记录"><Trash2 size={15} /></button></div>{expanded === session.id && <div className="mt-4 border-t border-line pt-4"><p className="text-sm leading-6 text-muted">{session.improvement}</p>{session.userMessages.length > 0 && <div className="mt-3 rounded-xl bg-canvas p-3"><p className="text-[11px] font-bold text-muted">最近一次回答</p><p className="mt-1 text-sm">{session.userMessages[session.userMessages.length - 1]?.text}</p></div>}</div>}</article>)}</div>}</section>;
}
