import type { MediaItem } from "./types";

const tmdbSearchUrl = (title: string) => `https://www.themoviedb.org/search?query=${encodeURIComponent(title)}`;

export const fallbackMedia: MediaItem[] = [
  { id: "fallback-eeaao", mediaType: "movie", category: "movie", title: "瞬息全宇宙", originalTitle: "Everything Everywhere All at Once", releaseDate: "2022", country: "美国", genres: ["科幻", "喜剧", "剧情"], cast: ["杨紫琼", "关继威"], overview: "一位普通移民女性意外连接到多重宇宙中的不同人生，并在混乱中重新理解家庭与选择。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("Everything Everywhere All at Once"), aiReason: "适合喜欢高概念、家庭关系和黑色幽默的观众。周末或想看一部节奏丰富、讨论空间很大的电影时可以选择。" },
  { id: "fallback-oppenheimer", mediaType: "movie", category: "movie", title: "奥本海默", originalTitle: "Oppenheimer", releaseDate: "2023", country: "美国", genres: ["剧情", "历史"], cast: ["基里安·墨菲", "艾米莉·布朗特"], overview: "科学家 J. Robert Oppenheimer 参与曼哈顿计划，并面对科学、责任与历史后果之间的复杂关系。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("Oppenheimer"), aiReason: "适合喜欢历史题材、人物传记和严肃叙事的观众。建议在时间充裕、希望集中观看时打开。" },
  { id: "fallback-dune2", mediaType: "movie", category: "movie", title: "沙丘2", originalTitle: "Dune: Part Two", releaseDate: "2024", country: "美国 / 加拿大", genres: ["科幻", "冒险", "剧情"], cast: ["提莫西·查拉梅", "赞达亚"], overview: "保罗·厄崔迪与契妮及弗雷曼人联手踏上复仇之路，并面对成为预言中心人物的命运。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("Dune Part Two"), aiReason: "适合喜欢宏大世界观、政治寓言和史诗视觉的观众。最好在安静且连续的观看时间里体验。" },
  { id: "fallback-spiderverse", mediaType: "movie", category: "anime", title: "蜘蛛侠：纵横宇宙", originalTitle: "Spider-Man: Across the Spider-Verse", releaseDate: "2023", country: "美国", genres: ["动画", "动作", "科幻"], cast: ["沙梅克·摩尔", "海莉·斯坦菲尔德"], overview: "迈尔斯·莫拉莱斯进入更广阔的蜘蛛侠宇宙，并在不同选择与责任之间寻找自己的道路。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("Spider-Man Across the Spider-Verse"), aiReason: "适合喜欢动画创新、超级英雄和成长主题的观众。适合周末晚上观看，视觉风格尤其值得关注。" },
  { id: "fallback-godfather", mediaType: "movie", category: "movie", title: "教父", originalTitle: "The Godfather", releaseDate: "1972", country: "美国", genres: ["剧情", "犯罪"], cast: ["马龙·白兰度", "阿尔·帕西诺"], overview: "一个意大利裔美国黑手党家族在权力交接与家庭责任之间经历变化。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("The Godfather"), aiReason: "适合想补经典电影、喜欢人物群像和慢节奏叙事的观众。适合在不被打扰的夜晚观看。" },
  { id: "fallback-wildrobot", mediaType: "movie", category: "anime", title: "荒野机器人", originalTitle: "The Wild Robot", releaseDate: "2024", country: "美国", genres: ["动画", "家庭", "科幻"], cast: ["露皮塔·尼永奥", "佩德罗·帕斯卡"], overview: "一台机器人在荒岛上醒来，并在与动物相处的过程中学习照顾与连接。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("The Wild Robot"), aiReason: "适合喜欢温柔成长故事、家庭动画和自然主题的观众。适合周末下午或与家人一起观看。" },
  { id: "fallback-shogun", mediaType: "tv", category: "tv", title: "幕府将军", originalTitle: "Shōgun", releaseDate: "2024", country: "美国 / 日本", genres: ["剧情", "历史", "战争"], cast: ["真田广之", "安娜·萨瓦伊"], overview: "一名英国航海家来到日本后，被卷入地方领主之间的权力斗争与文化碰撞。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("Shogun"), aiReason: "适合喜欢历史剧、权力博弈和多文化叙事的观众。适合连续观看，人物关系需要一点耐心。" },
  { id: "fallback-bear", mediaType: "tv", category: "tv", title: "熊家餐馆", originalTitle: "The Bear", releaseDate: "2022", country: "美国", genres: ["剧情", "喜剧"], cast: ["杰瑞米·艾伦·怀特", "艾邦·摩斯-巴克拉赫"], overview: "一位年轻厨师回到芝加哥接手家族三明治店，在高压厨房中重新面对家庭与团队。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("The Bear"), aiReason: "适合喜欢职场群像、快节奏对白和食物题材的观众。适合一次观看一两集，保留情绪消化空间。" },
  { id: "fallback-blue-eye", mediaType: "tv", category: "anime", title: "蓝眼武士", originalTitle: "Blue Eye Samurai", releaseDate: "2023", country: "美国", genres: ["动画", "动作", "剧情"], cast: ["玛雅·厄斯金", "乔治·武井"], overview: "一名混血剑客在江户时代的日本踏上复仇之旅，并不断面对身份与选择。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("Blue Eye Samurai"), aiReason: "适合喜欢成人动画、动作设计和复仇叙事的观众。适合晚上连续观看，画面与人物都很有辨识度。" },
  { id: "fallback-planet-earth", mediaType: "tv", category: "documentary", title: "地球脉动3", originalTitle: "Planet Earth III", releaseDate: "2023", country: "英国", genres: ["纪录片", "自然"], cast: ["大卫·爱登堡"], overview: "纪录片以新的影像技术记录地球不同环境中的动物、生态与生存挑战。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("Planet Earth III"), aiReason: "适合喜欢自然影像、科学知识和慢节奏观看的观众。适合周末白天观看，也适合用作放松时的单集选择。" },
  { id: "fallback-clarksons-farm", mediaType: "tv", category: "variety", title: "克拉克森的农场", originalTitle: "Clarkson's Farm", releaseDate: "2021", country: "英国", genres: ["真人秀", "喜剧"], cast: ["杰里米·克拉克森"], overview: "电视主持人尝试经营农场，在天气、动物、作物和现实经营之间不断学习。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("Clarkson's Farm"), aiReason: "适合喜欢真人秀、乡村生活和轻松幽默的观众。适合晚餐后观看，单集节奏比较轻松。" },
  { id: "fallback-3body", mediaType: "tv", category: "tv", title: "三体", originalTitle: "3 Body Problem", releaseDate: "2024", country: "美国 / 英国", genres: ["科幻", "剧情", "悬疑"], cast: ["杰西·洪", "艾莎·冈萨雷斯"], overview: "一群科学家面对一项跨越时间与空间的未知威胁，科学规律与人类选择开始发生变化。", sourceName: "TMDB 公开资料", sourceUrl: tmdbSearchUrl("3 Body Problem"), aiReason: "适合喜欢科幻谜题、科学设定和连续剧悬念的观众。适合有完整时间时连续观看，避免被剧透。" },
];

export const fallbackById = new Map(fallbackMedia.map((item) => [item.id, item]));
