export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          avatar_url: string | null;
          timezone: string;
          language: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          language?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          language?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      devices: {
        Row: {
          id: string;
          user_id: string;
          device_name: string;
          device_type: string;
          platform: string;
          last_seen_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          device_name: string;
          device_type?: string;
          platform?: string;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          device_name?: string;
          device_type?: string;
          platform?: string;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_data_items: {
        Row: {
          id: string;
          user_id: string;
          module: string;
          item_type: string;
          entity_id: string;
          state: string;
          payload: Json;
          source_storage_key: string;
          source_device_id: string | null;
          version: number;
          client_updated_at: string;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          module: string;
          item_type: string;
          entity_id: string;
          state: string;
          payload?: Json;
          source_storage_key: string;
          source_device_id?: string | null;
          version?: number;
          client_updated_at?: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          module?: string;
          item_type?: string;
          entity_id?: string;
          state?: string;
          payload?: Json;
          source_storage_key?: string;
          source_device_id?: string | null;
          version?: number;
          client_updated_at?: string;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_migration_runs: {
        Row: {
          id: string;
          user_id: string;
          migration_key: string;
          source_device_id: string | null;
          status: string;
          item_count: number;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          migration_key: string;
          source_device_id?: string | null;
          status?: string;
          item_count?: number;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          migration_key?: string;
          source_device_id?: string | null;
          status?: string;
          item_count?: number;
          completed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      plan_tasks: {
        Row: {
          id: string;
          user_id: string;
          local_id: string;
          source_device_id: string | null;
          title: string;
          task_date: string;
          task_time: string | null;
          priority: string;
          category: string;
          notes: string;
          completed: boolean;
          completed_at: string | null;
          source_storage_key: string;
          version: number;
          client_created_at: string;
          client_updated_at: string;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          local_id: string;
          source_device_id?: string | null;
          title: string;
          task_date: string;
          task_time?: string | null;
          priority?: string;
          category?: string;
          notes?: string;
          completed?: boolean;
          completed_at?: string | null;
          source_storage_key?: string;
          version?: number;
          client_created_at: string;
          client_updated_at: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          local_id?: string;
          source_device_id?: string | null;
          title?: string;
          task_date?: string;
          task_time?: string | null;
          priority?: string;
          category?: string;
          notes?: string;
          completed?: boolean;
          completed_at?: string | null;
          source_storage_key?: string;
          version?: number;
          client_created_at?: string;
          client_updated_at?: string;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      exercise_types: {
        Row: {
          id: string;
          user_id: string;
          local_id: string;
          source_device_id: string | null;
          name: string;
          icon: string;
          sort_order: number;
          is_favorite: boolean;
          is_active: boolean;
          source_storage_key: string;
          version: number;
          client_created_at: string;
          client_updated_at: string;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          local_id: string;
          source_device_id?: string | null;
          name: string;
          icon?: string;
          sort_order?: number;
          is_favorite?: boolean;
          is_active?: boolean;
          source_storage_key?: string;
          version?: number;
          client_created_at: string;
          client_updated_at: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          local_id?: string;
          source_device_id?: string | null;
          name?: string;
          icon?: string;
          sort_order?: number;
          is_favorite?: boolean;
          is_active?: boolean;
          source_storage_key?: string;
          version?: number;
          client_created_at?: string;
          client_updated_at?: string;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      exercise_records: {
        Row: {
          id: string;
          user_id: string;
          local_id: string;
          source_device_id: string | null;
          type_local_id: string;
          exercise_date: string;
          start_time: string | null;
          duration_minutes: number | null;
          location: string | null;
          intensity: string | null;
          feeling: string | null;
          note: string | null;
          image_url: string | null;
          source_storage_key: string;
          version: number;
          client_created_at: string;
          client_updated_at: string;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          local_id: string;
          source_device_id?: string | null;
          type_local_id: string;
          exercise_date: string;
          start_time?: string | null;
          duration_minutes?: number | null;
          location?: string | null;
          intensity?: string | null;
          feeling?: string | null;
          note?: string | null;
          image_url?: string | null;
          source_storage_key?: string;
          version?: number;
          client_created_at: string;
          client_updated_at: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          local_id?: string;
          source_device_id?: string | null;
          type_local_id?: string;
          exercise_date?: string;
          start_time?: string | null;
          duration_minutes?: number | null;
          location?: string | null;
          intensity?: string | null;
          feeling?: string | null;
          note?: string | null;
          image_url?: string | null;
          source_storage_key?: string;
          version?: number;
          client_created_at?: string;
          client_updated_at?: string;
          deleted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
